/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.70
 * Generated at: 2023-01-13 08:42:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.myPage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class myPage_005fBrand_005fInfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("/WEB-INF/views/myPage/../common/footer.jsp", Long.valueOf(1673597237028L));
    _jspx_dependants.put("jar:file:/C:/ThisIsJavaSecondEdition/eclipse-workspace/project3_team3/apache-tomcat-9_0_70/wtpwebapps/YKJK/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/myPage/myPage_Brand_Menu.jsp", Long.valueOf(1673597237028L));
    _jspx_dependants.put("jar:file:/C:/ThisIsJavaSecondEdition/eclipse-workspace/project3_team3/apache-tomcat-9_0_70/wtpwebapps/YKJK/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1673597237028L));
    _jspx_dependants.put("jar:file:/C:/ThisIsJavaSecondEdition/eclipse-workspace/project3_team3/apache-tomcat-9_0_70/wtpwebapps/YKJK/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("	<head>\r\n");
      out.write("	    <meta charset=\"UTF-8\">\r\n");
      out.write("	    <title>OOTD - 마이페이지(브랜드)</title>\r\n");
      out.write("	    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/asset/js/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("	    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/myPage_Info.css\">\r\n");
      out.write("	    ");
      if (_jspx_meth_c_005fimport_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<!-- HEADER IMPORT -->\r\n");
      out.write("	");
      if (_jspx_meth_c_005fimport_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"container-myPage\">\r\n");
      out.write("        <div class=\"body-title\">MY PAGE</div>\r\n");
      out.write("       \r\n");
      out.write("        <!-- 좌측 aside 메뉴 (BRAND)-->\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <aside class=\"category-list\">\r\n");
      out.write("		<div class=\"menu-title\">MY PAGE</div>\r\n");
      out.write("		<ul class=\"category\">\r\n");
      out.write("		    <li>\r\n");
      out.write("		        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/myPage/myPage_Brand_Info.mp\" style=\"text-decoration: none; color: black;\">회원 정보</a>\r\n");
      out.write("		    </li>\r\n");
      out.write("		    <li>\r\n");
      out.write("		        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/myPage/myPage_Brand_Product.mp\" style=\"text-decoration: none; color: black;\">등록 상품</a>\r\n");
      out.write("		    </li>\r\n");
      out.write("		    <li>\r\n");
      out.write("		        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/myPage/myPage_Brand_Order.mp\" style=\"text-decoration: none; color: black;\">주문 내역</a>\r\n");
      out.write("		    </li>\r\n");
      out.write("		    <li>\r\n");
      out.write("		        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/myPage/myPage_Brand_Rank.mp\" style=\"text-decoration: none; color: black;\">상품 순위</a>\r\n");
      out.write("		    </li>\r\n");
      out.write("		</ul>\r\n");
      out.write("	</aside>");
      out.write("\r\n");
      out.write("     \r\n");
      out.write("        <section class=\"main\">\r\n");
      out.write("            <div class=\"wrap-section\">\r\n");
      out.write("                <div class=\"table-title\">브랜드 정보</div>\r\n");
      out.write("                <table class=\"member-info\">\r\n");
      out.write("                    <tbody>\r\n");
      out.write("                        <tr class=\"id\">\r\n");
      out.write("                            <td>아이디</td>\r\n");
      out.write("                            <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.member_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                            <td></td>\r\n");
      out.write("                            <td></td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr class=\"password\">\r\n");
      out.write("                            <td>비밀번호</td>\r\n");
      out.write("                            <td colspan=\"2\"><input type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.member_pw}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">*********</td>\r\n");
      out.write("                            <td>\r\n");
      out.write("                                <button class=\"modify-btn\" id=\"update-password\">비밀번호 변경</button>\r\n");
      out.write("                            </td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr class=\"update-password\" style=\"display: none\">\r\n");
      out.write("\r\n");
      out.write("                            <td colspan=\"4\">\r\n");
      out.write("                                <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/myPage/myPage_Brand_Info_pwUpdate.mp\" method=\"post\">\r\n");
      out.write("                                    <div class='passowrd-update-area'>\r\n");
      out.write("                                        <div class=\"input\">\r\n");
      out.write("                                            <label for=\"password\">현재 비밀번호</label>\r\n");
      out.write("                                            <input type=\"password\" name=\"password\" id=\"password\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"input\">\r\n");
      out.write("                                            <label for=\"new-password\">새 비밀번호</label>\r\n");
      out.write("                                            <input type=\"password\" class=\"pw\" name=\"new_password\" id=\"new_password\">\r\n");
      out.write("                                        </div>          \r\n");
      out.write("                                        <div class=\"input\">\r\n");
      out.write("                                            <label for=\"new-password-confirm\">새 비밀번호 확인</label>\r\n");
      out.write("                                            <input type=\"password\" class=\"pw\" name=\"new_password_confirm\" id=\"new_password_confirm\">\r\n");
      out.write("                                              <span id=\"alert-success\" style=\"display: inline-block; color: #6e6e6e;\">&nbsp;비밀번호가 일치합니다.</span>\r\n");
      out.write("    										  <span id=\"alert-danger\" style=\"display: inline-block;  color: #FF5A5A;\">&nbsp;비밀번호가 일치하지 않습니다.</span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"btn-group\">\r\n");
      out.write("                                            <input type=\"submit\" class=\"submit1\" value=\"확인\">\r\n");
      out.write("                                            <input type=\"reset\" id=\"reset-password\" value=\"취소\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </form>\r\n");
      out.write("                            </td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>브랜드명</td>\r\n");
      out.write("                            <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.brand_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                            <td></td>\r\n");
      out.write("                            <td></td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr class='email'>\r\n");
      out.write("                            <td>대표 이메일</td>\r\n");
      out.write("                            <td colspan=\"2\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                            <td>\r\n");
      out.write("                                <button id=\"update-email\">이메일 변경</button>\r\n");
      out.write("                            </td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr class=\"update-email\" style=\"display: none\">\r\n");
      out.write("\r\n");
      out.write("                            <td colspan=\"4\">\r\n");
      out.write("                                <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/myPage/myPage_Brand_Info_emUpdate.mp\" method=\"post\">\r\n");
      out.write("                                    <div class='email-update-area'>\r\n");
      out.write("                                        <div class=\"input\">\r\n");
      out.write("                                            <label for=\"email\">변경 이메일 주소</label>\r\n");
      out.write("                                            <input type=\"email\" name=\"email\" id=\"email\"\r\n");
      out.write("                                                placeholder=\"변경 이메일 주소 입력(example@ootd.com)\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("\r\n");
      out.write("                                        <div class=\"btn-group\">\r\n");
      out.write("                                            <input type=\"submit\" value=\"확인\">\r\n");
      out.write("                                            <input type=\"reset\" id=\"reset-email\" value=\"취소\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </form>\r\n");
      out.write("                            </td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr class=\"phone\">\r\n");
      out.write("                            <td>대표전화</td>\r\n");
      out.write("                            <td colspan=\"2\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.phone}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                            <td>\r\n");
      out.write("                                <button id=\"update-phone\">전화번호 변경</button>\r\n");
      out.write("                            </td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr class=\"update-phone\" style=\"display: none\">\r\n");
      out.write("                            <td colspan=\"4\">\r\n");
      out.write("                                <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/myPage/myPage_Brand_Info_phUpdate.mp\" method=\"post\">\r\n");
      out.write("                                    <div class='phone-update-area'>\r\n");
      out.write("                                        <div class=\"input\">\r\n");
      out.write("                                            <label for=\"phone\">변경 번호</label>\r\n");
      out.write("                                            <input type=\"text\" name=\"phone\" id=\"phone\"\r\n");
      out.write("                                                placeholder=\"휴대전화 번호 입력( ' - ' 포함)\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"btn-group\">\r\n");
      out.write("                                            <input type=\"submit\" value=\"확인\">\r\n");
      out.write("                                            <input type=\"reset\" id=\"reset-phone\" value=\"취소\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </form>\r\n");
      out.write("                            </td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr class=\"account\">\r\n");
      out.write("                            <td>계좌번호</td>\r\n");
      out.write("                            <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.bank_code}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                            <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.account_number}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                            <td>\r\n");
      out.write("                                <button id=\"update-account\">계좌번호 변경</button>\r\n");
      out.write("                            </td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr class=\"update-account\" style=\"display: none\">\r\n");
      out.write("\r\n");
      out.write("                            <td colspan=\"4\">\r\n");
      out.write("                                <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/myPage/myPage_Brand_Info_accountUpdate.mp\" method=\"post\">\r\n");
      out.write("                                    <div class='account-update-area'>\r\n");
      out.write("                                        <div class=\"input\">\r\n");
      out.write("                                            <label for=\"account\">변경 계좌번호</label>\r\n");
      out.write("\r\n");
      out.write("                                            <select class=\"select-bank\" name=\"bank_code\">\r\n");
      out.write("                                                 <option value=\"NH\">농협</option>\r\n");
      out.write("				                                 <option value=\"KB\">KB</option>\r\n");
      out.write("				                                 <option value=\"SH\">신한</option>\r\n");
      out.write("				                                 <option value=\"UR\">우리</option>\r\n");
      out.write("				                                 <option value=\"CH\">축협</option>\r\n");
      out.write("				                                 <option value=\"SH\">수협</option>\r\n");
      out.write("				                                 <option value=\"IBK\">IBK</option>\r\n");
      out.write("                                            </select>       \r\n");
      out.write("\r\n");
      out.write("                                            <input type=\"text\" name=\"account_number\" id=\"account\"\r\n");
      out.write("                                                placeholder=\"계좌번호 입력( ' - ' 포함)\">\r\n");
      out.write("\r\n");
      out.write("                                            <div class=\"btn-group\">\r\n");
      out.write("                                                <input type=\"submit\" value=\"확인\">\r\n");
      out.write("                                                <input type=\"reset\" id=\"reset-account\" value=\"취소\">\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </form>\r\n");
      out.write("                            </td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </tbody>\r\n");
      out.write("                </table>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </section>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <!-- FOOTER IMPORT -->\r\n");
      out.write("   	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/footer.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<footer class=\"footer\">\r\n");
      out.write("        <div class=\"wrapper\">\r\n");
      out.write("        \r\n");
      out.write("            <div class=\"footer_contents\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"content\">\r\n");
      out.write("                    <div class=\"title\">\r\n");
      out.write("                        <h3>YKJK</h3>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"company\">\r\n");
      out.write("                        <p>\r\n");
      out.write("                            YKJK 경기도 안산시 상록구 광덕1로 375 강우프라자 <br>\r\n");
      out.write("                            대표 : 곽해준 <br>\r\n");
      out.write("                            사업자 등록번호 : 123-45-67890 <br>\r\n");
      out.write("                            통신판매업신고 : 2023-경기안산-0113 <br>\r\n");
      out.write("                            help@ykjk.com <br>\r\n");
      out.write("                            copyright &copy; 2023 YKJK Inc.\r\n");
      out.write("                        </p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                \r\n");
      out.write("\r\n");
      out.write("                    <div class=\"customer_center\">\r\n");
      out.write("                        <h3>CUSTOMER CENTER</h3>\r\n");
      out.write("                        <h3>010-1234-5678</h3>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"officeHour\">\r\n");
      out.write("                        <p>\r\n");
      out.write("                            평일 오전 9시 - 오후 6시 <br>\r\n");
      out.write("                            점심시간 오후 12시 - 14시 <br>\r\n");
      out.write("                            주말, 공휴일 휴무\r\n");
      out.write("                        </p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("    <script>\r\n");
      out.write("    $(\"#logo_footer\").on(\"click\",function(){\r\n");
      out.write("		location.href = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product/ending.do\";\r\n");
      out.write("		});\r\n");
      out.write("    </script>\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("   	\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("    $('#update-password').on('click', function () {\r\n");
      out.write("        $('.update-password').show()\r\n");
      out.write("        $('.password').hide()\r\n");
      out.write("    })\r\n");
      out.write("\r\n");
      out.write("    $('#reset-password').on('click', function () {\r\n");
      out.write("        $('.update-password').hide()\r\n");
      out.write("        $('.password').show()\r\n");
      out.write("    })\r\n");
      out.write("\r\n");
      out.write("    $('#update-email').on('click', function () {\r\n");
      out.write("        $('.update-email').show()\r\n");
      out.write("        $('.email').hide()\r\n");
      out.write("    })\r\n");
      out.write("\r\n");
      out.write("    $('#reset-email').on('click', function () {\r\n");
      out.write("        $('.update-email').hide()\r\n");
      out.write("        $('.email').show()\r\n");
      out.write("    })\r\n");
      out.write("\r\n");
      out.write("    $('#update-phone').on('click', function () {\r\n");
      out.write("        $('.update-phone').show()\r\n");
      out.write("        $('.phone').hide()\r\n");
      out.write("    })\r\n");
      out.write("\r\n");
      out.write("    $('#reset-phone').on('click', function () {\r\n");
      out.write("        $('.update-phone').hide()\r\n");
      out.write("        $('.phone').show()\r\n");
      out.write("    })\r\n");
      out.write("\r\n");
      out.write("    $('#update-account').on('click', function () {\r\n");
      out.write("        $('.update-account').show()\r\n");
      out.write("        $('.account').hide()\r\n");
      out.write("    })\r\n");
      out.write("\r\n");
      out.write("    $('#reset-account').on('click', function () {\r\n");
      out.write("        $('.update-account').hide()\r\n");
      out.write("        $('.account').show()\r\n");
      out.write("    })\r\n");
      out.write("   \r\n");
      out.write("   	$(function(){\r\n");
      out.write("   		$('#alert-success').hide();\r\n");
      out.write("   		$('#alert-danger').hide();\r\n");
      out.write("   		$('.pw').keyup(function(){\r\n");
      out.write("   			var pwd1 = $('#new_password').val();\r\n");
      out.write("   	   		var pwd2 = $('#new_password_confirm').val();\r\n");
      out.write("   	   		console.log(pwd1);\r\n");
      out.write("   	   		console.log(pwd2);\r\n");
      out.write("   			if(pwd1 != \"\" || pwd2 != \"\"){\r\n");
      out.write("   				if(pwd1 == pwd2){\r\n");
      out.write("   					$('#alert-success').show();\r\n");
      out.write("   					$('#alert-danger').hide();\r\n");
      out.write("   					$('.submit1').removeAttr('disabled');\r\n");
      out.write("   				} else {\r\n");
      out.write("   					$('#alert-success').hide();\r\n");
      out.write("   					$('#alert-danger').show();\r\n");
      out.write("   					$('.submit1').attr('disabled', 'disabled');\r\n");
      out.write("   				}\r\n");
      out.write("   			}\r\n");
      out.write("   		});   		\r\n");
      out.write("   		\r\n");
      out.write("   	});\r\n");
      out.write("   	\r\n");
      out.write("   		\r\n");
      out.write("   	\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fimport_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f0 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f0_reused = false;
    try {
      _jspx_th_c_005fimport_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f0.setParent(null);
      // /WEB-INF/views/myPage/myPage_Brand_Info.jsp(14,5) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f0.setUrl("../common/styler.jsp");
      int[] _jspx_push_body_count_c_005fimport_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f0 = _jspx_th_c_005fimport_005f0.doStartTag();
        if (_jspx_th_c_005fimport_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f0);
      _jspx_th_c_005fimport_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fimport_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f1 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f1_reused = false;
    try {
      _jspx_th_c_005fimport_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f1.setParent(null);
      // /WEB-INF/views/myPage/myPage_Brand_Info.jsp(19,1) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f1.setUrl("../common/header.jsp");
      int[] _jspx_push_body_count_c_005fimport_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f1 = _jspx_th_c_005fimport_005f1.doStartTag();
        if (_jspx_th_c_005fimport_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f1);
      _jspx_th_c_005fimport_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f1_reused);
    }
    return false;
  }
}
