/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.70
 * Generated at: 2023-01-13 08:42:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.myPage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class myPage_005fBrand_005fOrder_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(7);
    _jspx_dependants.put("/WEB-INF/views/myPage/myPage_Order_Detail.jsp", Long.valueOf(1673597237028L));
    _jspx_dependants.put("/WEB-INF/views/myPage/../common/footer.jsp", Long.valueOf(1673597237028L));
    _jspx_dependants.put("jar:file:/C:/ThisIsJavaSecondEdition/eclipse-workspace/project3_team3/apache-tomcat-9_0_70/wtpwebapps/YKJK/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/myPage/myPage_Brand_Menu.jsp", Long.valueOf(1673597237028L));
    _jspx_dependants.put("jar:file:/C:/ThisIsJavaSecondEdition/eclipse-workspace/project3_team3/apache-tomcat-9_0_70/wtpwebapps/YKJK/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1673597237028L));
    _jspx_dependants.put("jar:file:/C:/ThisIsJavaSecondEdition/eclipse-workspace/project3_team3/apache-tomcat-9_0_70/wtpwebapps/YKJK/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fescapeXml_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fescapeXml_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fescapeXml_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("	<head>\r\n");
      out.write("	    <meta charset=\"UTF-8\">\r\n");
      out.write("	    <title>브랜드 - 주문 내역</title>\r\n");
      out.write("	    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/asset/js/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("	    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/myPage.css\">\r\n");
      out.write("	    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/order_Detail.css\">\r\n");
      out.write("	    ");
      if (_jspx_meth_c_005fimport_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<!-- HEADER IMPORT -->\r\n");
      out.write("	");
      if (_jspx_meth_c_005fimport_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container-myPage\">\r\n");
      out.write("        <div class=\"body-title\">MY PAGE</div>\r\n");
      out.write("        \r\n");
      out.write("        <!-- 좌측 aside 메뉴 (BRAND)-->\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <aside class=\"category-list\">\r\n");
      out.write("		<div class=\"menu-title\">MY PAGE</div>\r\n");
      out.write("		<ul class=\"category\">\r\n");
      out.write("		    <li>\r\n");
      out.write("		        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/myPage/myPage_Brand_Info.mp\" style=\"text-decoration: none; color: black;\">회원 정보</a>\r\n");
      out.write("		    </li>\r\n");
      out.write("		    <li>\r\n");
      out.write("		        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/myPage/myPage_Brand_Product.mp\" style=\"text-decoration: none; color: black;\">등록 상품</a>\r\n");
      out.write("		    </li>\r\n");
      out.write("		    <li>\r\n");
      out.write("		        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/myPage/myPage_Brand_Order.mp\" style=\"text-decoration: none; color: black;\">주문 내역</a>\r\n");
      out.write("		    </li>\r\n");
      out.write("		    <li>\r\n");
      out.write("		        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/myPage/myPage_Brand_Rank.mp\" style=\"text-decoration: none; color: black;\">상품 순위</a>\r\n");
      out.write("		    </li>\r\n");
      out.write("		</ul>\r\n");
      out.write("	</aside>");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        <section class=\"main\">\r\n");
      out.write("            <div class=\"wrap-section\">\r\n");
      out.write("                <div class=\"table-title\">Order List</div>\r\n");
      out.write("                <table class=\"order-list\">\r\n");
      out.write("                    <thead>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <th>상품명</th>\r\n");
      out.write("                            <th>수량</th>\r\n");
      out.write("                            <th>주문번호</th>\r\n");
      out.write("                            <th>주문일자</th>\r\n");
      out.write("                            <th>판매금액</th>\r\n");
      out.write("                            <th>주문상태</th>\r\n");
      out.write("                            <th></th>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </thead>\r\n");
      out.write("                    ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                </table>\r\n");
      out.write("                ");
      if (_jspx_meth_c_005fout_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("   	<!-- Order Detail(Mordal) -->\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"modal\">\r\n");
      out.write("        <div class=\"order-detail\">\r\n");
      out.write("            <div class=\"close-icon\">\r\n");
      out.write("                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/icon/close_icon.png\" alt=\"close icon\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"detail-area\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"detail-title\">ORDER DETAIL</div>\r\n");
      out.write("                <div class=\"order-no-area\">\r\n");
      out.write("                    <span>No.</span>\r\n");
      out.write("                    <span class=\"order-no\">0000001</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"customer-info-title detail-subtitle\">Customer Info</div>\r\n");
      out.write("                <table class=\"customer-info\">\r\n");
      out.write("                    <thead>\r\n");
      out.write("                        <tr style=\"text-align: center;\">\r\n");
      out.write("                            <th>주문자명</th>\r\n");
      out.write("                            <th>배송주소</th>\r\n");
      out.write("                            <th>연락처</th>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </thead>\r\n");
      out.write("                    <tbody>\r\n");
      out.write("                        <tr style=\"text-align: center;\">\r\n");
      out.write("                            <td>\r\n");
      out.write("                                <div class=\"customer-name\">옷삼이</div>\r\n");
      out.write("                            </td>\r\n");
      out.write("                            <td>\r\n");
      out.write("                                <div class=\"customer-address\">서울시 강남구 옷삼로333, 21 2층</div>\r\n");
      out.write("                            </td>\r\n");
      out.write("                            <td>\r\n");
      out.write("                                <div class=\"customer-phone\">010-1234-1234</div>\r\n");
      out.write("                            </td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </tbody>\r\n");
      out.write("                </table>\r\n");
      out.write("                <div class=\"product-info-title detail-subtitle\">Ordered Item</div>\r\n");
      out.write("                <table class=\"order-list\">\r\n");
      out.write("                    <thead>\r\n");
      out.write("                        <tr style=\"text-align: center;\">\r\n");
      out.write("                            <th>상품명</th>\r\n");
      out.write("                            <th>주문일자</th>\r\n");
      out.write("                            <th>수량</th>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </thead>\r\n");
      out.write("                    <tbody>\r\n");
      out.write("                        <tr style=\"text-align: center;\">\r\n");
      out.write("                            <td class=\"modal-product\">\r\n");
      out.write("                                <span class=\"product-name\">Round String Jacket Brown </span>\r\n");
      out.write("                                <span class=\"product-option\">(small)</span>\r\n");
      out.write("                            </td>\r\n");
      out.write("                            <td class=\"modal-date\">\r\n");
      out.write("                                <div class=\"order-date\">2021.06.06</div>\r\n");
      out.write("                            </td>\r\n");
      out.write("                            <td class=\"modal-quantity\">\r\n");
      out.write("                                <div class=\"order-quantity\">3</div>\r\n");
      out.write("                            </td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </tbody>\r\n");
      out.write("                </table>\r\n");
      out.write("                <div class=\"price-area\">\r\n");
      out.write("                    <span>주문금액 : </span>\r\n");
      out.write("                    <span class=\"price-amount\">200,000&nbsp;&#8361;</span><span>&nbsp;&#8361;</span>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    // 모달창 스크립트\r\n");
      out.write("    $('.order-no').click(function () {\r\n");
      out.write("        $('.modal').fadeIn();\r\n");
      out.write("    })\r\n");
      out.write("\r\n");
      out.write("    $('.modal').on('click', function (event) {\r\n");
      out.write("        if ($(event.target).hasClass('modal')) {\r\n");
      out.write("            $('.modal').fadeOut()\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("    $('.close-icon').click(function () {\r\n");
      out.write("        $('.modal').fadeOut();\r\n");
      out.write("    })\r\n");
      out.write("\r\n");
      out.write("</script>");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("        \r\n");
      out.write("    <!-- FOOTER IMPORT -->\r\n");
      out.write("   	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/footer.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<footer class=\"footer\">\r\n");
      out.write("        <div class=\"wrapper\">\r\n");
      out.write("        \r\n");
      out.write("            <div class=\"footer_contents\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"content\">\r\n");
      out.write("                    <div class=\"title\">\r\n");
      out.write("                        <h3>YKJK</h3>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"company\">\r\n");
      out.write("                        <p>\r\n");
      out.write("                            YKJK 경기도 안산시 상록구 광덕1로 375 강우프라자 <br>\r\n");
      out.write("                            대표 : 곽해준 <br>\r\n");
      out.write("                            사업자 등록번호 : 123-45-67890 <br>\r\n");
      out.write("                            통신판매업신고 : 2023-경기안산-0113 <br>\r\n");
      out.write("                            help@ykjk.com <br>\r\n");
      out.write("                            copyright &copy; 2023 YKJK Inc.\r\n");
      out.write("                        </p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                \r\n");
      out.write("\r\n");
      out.write("                    <div class=\"customer_center\">\r\n");
      out.write("                        <h3>CUSTOMER CENTER</h3>\r\n");
      out.write("                        <h3>010-1234-5678</h3>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"officeHour\">\r\n");
      out.write("                        <p>\r\n");
      out.write("                            평일 오전 9시 - 오후 6시 <br>\r\n");
      out.write("                            점심시간 오후 12시 - 14시 <br>\r\n");
      out.write("                            주말, 공휴일 휴무\r\n");
      out.write("                        </p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("    <script>\r\n");
      out.write("    $(\"#logo_footer\").on(\"click\",function(){\r\n");
      out.write("		location.href = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product/ending.do\";\r\n");
      out.write("		});\r\n");
      out.write("    </script>\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("   	\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("	var ps;\r\n");
      out.write("    // 모달창 스크립트\r\n");
      out.write("    $('.order-no').click(function () {\r\n");
      out.write("        $('.modal').fadeIn();\r\n");
      out.write("        var a = $(this).text();\r\n");
      out.write("	    console.log(a);\r\n");
      out.write("        // console.log($(this).text());\r\n");
      out.write("    })\r\n");
      out.write("\r\n");
      out.write("    $('.modal').on('click', function (event) {\r\n");
      out.write("        if ($(event.target).hasClass('modal')) {\r\n");
      out.write("            $('.modal').fadeOut()\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    $('.close-icon').click(function () {\r\n");
      out.write("        $('.modal').fadeOut();\r\n");
      out.write("    })\r\n");
      out.write("\r\n");
      out.write("    // .purchase-status의 값(value)에 따라 배송 상태 텍스트 변경\r\n");
      out.write("    $(function () {\r\n");
      out.write("        $('.purchase-status').each(function () {\r\n");
      out.write("        	\r\n");
      out.write("            ps = $(this).text();\r\n");
      out.write("\r\n");
      out.write("            compSend = $(this).parent().next().children('.complete-send');\r\n");
      out.write("\r\n");
      out.write("            switch (ps) {\r\n");
      out.write("                case \"1\":\r\n");
      out.write("                    $(this).text('결제완료');\r\n");
      out.write("                    compSend.show();                    \r\n");
      out.write("                    break;\r\n");
      out.write("                case \"2\":\r\n");
      out.write("                    $(this).text('구매확정대기');\r\n");
      out.write("                    break;\r\n");
      out.write("                case \"3\":\r\n");
      out.write("                    $(this).text('거래완료');\r\n");
      out.write("                    break;\r\n");
      out.write("                case \"4\":\r\n");
      out.write("                    $(this).text('거래완료');\r\n");
      out.write("                    break;\r\n");
      out.write("            }\r\n");
      out.write("        })\r\n");
      out.write("        \r\n");
      out.write("        $('.pagination_r').css('padding-left', '33%');\r\n");
      out.write("    })\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("      \r\n");
      out.write("     $('.complete-send').click(function(){\r\n");
      out.write("    	 var orderNo = $(this).attr('id');\r\n");
      out.write("    	 var productNo = $(this).attr('name');\r\n");
      out.write("    	 console.log(\"pNo\", productNo);\r\n");
      out.write("    	 \r\n");
      out.write(" 		$.ajax({\r\n");
      out.write(" 			type: \"POST\",\r\n");
      out.write(" 			url: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/myPage/myPage_Brand_Send.mp\",\r\n");
      out.write(" 			data: { \"orderNo\" : orderNo, \"productNo\" : productNo}, \r\n");
      out.write("\r\n");
      out.write(" 			success: function(data){\r\n");
      out.write(" 				if(data == 2){\r\n");
      out.write(" 					//$(this).parent().siblings().children('.purchase-status').text('구매확정대기');\r\n");
      out.write(" 					//$(this).hide();\r\n");
      out.write(" 					location.reload();\r\n");
      out.write("                } else {\r\n");
      out.write("                	//$(this).parent().siblings().children('.purchase-status').text('결제완료');\r\n");
      out.write("                	location.reload();\r\n");
      out.write("                }\r\n");
      out.write(" 			}, 			\r\n");
      out.write(" 			error: function(){\r\n");
      out.write(" 				alert('상태 변환 실패!');\r\n");
      out.write(" 			}			\r\n");
      out.write(" 		});    	 \r\n");
      out.write("     });\r\n");
      out.write("    \r\n");
      out.write("    // 주문 번호를 클릭했을 때(span의 class가져옴)\r\n");
      out.write("	 $('.order-no').click(function(){\r\n");
      out.write("		 \r\n");
      out.write("		 var orderNo = $(this).text();\r\n");
      out.write("		 console.log(orderNo);\r\n");
      out.write("		 var productNo = $(this).attr('id');\r\n");
      out.write("    	 console.log(\"pNo\", productNo);\r\n");
      out.write("		 \r\n");
      out.write("		$.ajax({\r\n");
      out.write("			type: \"POST\",\r\n");
      out.write("			url: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/myPage/myPage_Order_Detail.mp\",\r\n");
      out.write("			data: { \"orderNo\" : orderNo, \"productNo\" : productNo }, \r\n");
      out.write("\r\n");
      out.write("			success: function(data){\r\n");
      out.write("				//alert('주문 상세보기 성공');\r\n");
      out.write("				console.log(data[0].order_no);\r\n");
      out.write("				console.log(data[0].receiver_name);\r\n");
      out.write("				console.log(data[0].order_date); // ? error\r\n");
      out.write("				$('.order-no-area>span.order-no').text(data[0].order_no);\r\n");
      out.write("				$('.customer-name').text(data[0].receiver_name);\r\n");
      out.write("				$('.customer-address').text(data[0].order_address);\r\n");
      out.write("				// $('.customer-phone').text(data[0].order_address);\r\n");
      out.write("				$('.modal-product>span.product-name').text(data[0].product_name);\r\n");
      out.write("				$('.customer-address').text(data[0].order_address);\r\n");
      out.write("				$('.modal-date>div.order-date').text(data[0].order_date);\r\n");
      out.write("				$('.modal-quantity>div.order-quantity').text(data[0].order_quantity);\r\n");
      out.write("				$('.price-area>span.price-amount').text(data[0].total_price);\r\n");
      out.write("			},\r\n");
      out.write("			\r\n");
      out.write("			error: function(){\r\n");
      out.write("				alert('주문 상세보기 실패');\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("		});\r\n");
      out.write("	}); \r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fimport_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f0 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f0_reused = false;
    try {
      _jspx_th_c_005fimport_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f0.setParent(null);
      // /WEB-INF/views/myPage/myPage_Brand_Order.jsp(16,5) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f0.setUrl("../common/styler.jsp");
      int[] _jspx_push_body_count_c_005fimport_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f0 = _jspx_th_c_005fimport_005f0.doStartTag();
        if (_jspx_th_c_005fimport_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f0);
      _jspx_th_c_005fimport_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fimport_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f1 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f1_reused = false;
    try {
      _jspx_th_c_005fimport_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f1.setParent(null);
      // /WEB-INF/views/myPage/myPage_Brand_Order.jsp(21,1) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f1.setUrl("../common/header.jsp");
      int[] _jspx_push_body_count_c_005fimport_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f1 = _jspx_th_c_005fimport_005f1.doStartTag();
        if (_jspx_th_c_005fimport_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f1);
      _jspx_th_c_005fimport_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/myPage/myPage_Brand_Order.jsp(44,20) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/myPage/myPage_Brand_Order.jsp(44,20) '${list}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${list}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/myPage/myPage_Brand_Order.jsp(44,20) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("o");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write(" \r\n");
            out.write("                    <tbody>\r\n");
            out.write("                        <tr>\r\n");
            out.write("                            <td>\r\n");
            out.write("                                <div class=\"product-info\">\r\n");
            out.write("                                    <span class=\"product-name\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.product_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span>\r\n");
            out.write("                                </div>\r\n");
            out.write("                            </td>\r\n");
            out.write("                            <td>\r\n");
            out.write("                                <div class=\"order-quantity\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.order_quantity}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</div>\r\n");
            out.write("                            </td>\r\n");
            out.write("                            <td>\r\n");
            out.write("                                <span class=\"order-no\" id=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.product_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.order_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span>\r\n");
            out.write("                            </td>\r\n");
            out.write("                            <td class=\"order-date\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.order_date}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("                            <td class=\"total-price\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.total_price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("&nbsp;&#8361;</td>\r\n");
            out.write("                            <td>\r\n");
            out.write("                                <span class=\"purchase-status\" >");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.order_status}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span> <!-- 값(숫자)에 따라 주문상태, 버튼 변경-->\r\n");
            out.write("                            </td>\r\n");
            out.write("                            <td>\r\n");
            out.write("                                <button class=\"complete-send\" id=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.order_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" name=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.product_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">발송 완료</button>\r\n");
            out.write("                            </td>\r\n");
            out.write("                        </tr>                                    \r\n");
            out.write("                    </tbody>\r\n");
            out.write("                    ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fescapeXml_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f0_reused = false;
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent(null);
      // /WEB-INF/views/myPage/myPage_Brand_Order.jsp(70,16) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageBar}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/views/myPage/myPage_Brand_Order.jsp(70,16) name = escapeXml type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setEscapeXml(false);
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fescapeXml_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      _jspx_th_c_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f0_reused);
    }
    return false;
  }
}
