/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.70
 * Generated at: 2023-01-27 01:54:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.product;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class brandDetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/C:/ThisIsJavaSecondEdition/eclipse-workspace/project3_team3/apache-tomcat-9_0_70/wtpwebapps/YKJK/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/ThisIsJavaSecondEdition/eclipse-workspace/project3_team3/apache-tomcat-9_0_70/wtpwebapps/YKJK/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1674781393797L));
    _jspx_dependants.put("jar:file:/C:/ThisIsJavaSecondEdition/eclipse-workspace/project3_team3/apache-tomcat-9_0_70/wtpwebapps/YKJK/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fescapeXml_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fescapeXml_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fescapeXml_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <!-- <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"> -->\r\n");
      out.write("    <title>brandDetail</title>\r\n");
      out.write("   \r\n");
      out.write("    ");
      if (_jspx_meth_c_005fimport_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("     <!-- Bootstrap CSS -->\r\n");
      out.write("    <!-- <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css\"\r\n");
      out.write("        integrity=\"sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l\" crossorigin=\"anonymous\"> -->\r\n");
      out.write("    <script src=\"http://code.jquery.com/jquery-latest.min.js\"></script>\r\n");
      out.write("    <script src='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery.zoom.js'></script>\r\n");
      out.write("    <script src='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery.Wheelzoom.js'></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/productDetail.css\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      if (_jspx_meth_c_005fimport_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("<section>\r\n");
      out.write("    <div class=\"product_detail\">\r\n");
      out.write("        <div class=\"package\" >\r\n");
      out.write("            <div id=\"insertArea\" class=\"inputBox1\">\r\n");
      out.write("            	");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div id=\"imgDetail\" class=\"inputBox2\">\r\n");
      out.write("                <div class='inputBox2 zoom' id='ex1'>\r\n");
      out.write("                    <img src='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/productImgUpload/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${a.att_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("' id='jack' width='540' height='620' alt=''/>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        \r\n");
      out.write("            \r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"package\">\r\n");
      out.write("            <div id=\"prTextInput\" class=\"inputBox3\">\r\n");
      out.write("                <span id=\"brand_name\"><b>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ product.brand_name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</b></span>\r\n");
      out.write("                <br>\r\n");
      out.write("                \r\n");
      out.write("                <h4 id=\"pName\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ product.product_name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h4>\r\n");
      out.write("                <span style=\"margin-left: 240px;\" >￦</span><span id=\"ppPrice\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ product.product_price }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span> <br><hr>\r\n");
      out.write("                \r\n");
      out.write("                <dl>\r\n");
      out.write("                    <dt class=\"drop\"><b>Product Detail</b> \r\n");
      out.write("                        <span class=\"accIcon\" style=\"float: right; margin-right: 30px;\"> \r\n");
      out.write("                            <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-plus-lg\" viewBox=\"0 0 16 16\">\r\n");
      out.write("                                <path d=\"M8 0a1 1 0 0 1 1 1v6h6a1 1 0 1 1 0 2H9v6a1 1 0 1 1-2 0V9H1a1 1 0 0 1 0-2h6V1a1 1 0 0 1 1-1z\"/>\r\n");
      out.write("                            </svg>\r\n");
      out.write("                            <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-dash-lg\" viewBox=\"0 0 16 16\">\r\n");
      out.write("                                <path d=\"M0 8a1 1 0 0 1 1-1h14a1 1 0 1 1 0 2H1a1 1 0 0 1-1-1z\"/>\r\n");
      out.write("                            </svg>\r\n");
      out.write("                        </span>\r\n");
      out.write("                    </dt> \r\n");
      out.write("                    <dd class=\"ddd\"><span class=\"pInfoText\">\r\n");
      out.write("                        ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ product.product_detail }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("                    </span> <br></dd>\r\n");
      out.write("                    <hr>\r\n");
      out.write("                    <dt class=\"drop\"><b>Size, Color</b> \r\n");
      out.write("                        <span class=\"accIcon\" style=\"float: right; margin-right: 30px;\">\r\n");
      out.write("                            <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-plus-lg\" viewBox=\"0 0 16 16\">\r\n");
      out.write("                                <path d=\"M8 0a1 1 0 0 1 1 1v6h6a1 1 0 1 1 0 2H9v6a1 1 0 1 1-2 0V9H1a1 1 0 0 1 0-2h6V1a1 1 0 0 1 1-1z\"/>\r\n");
      out.write("                            </svg>\r\n");
      out.write("                            <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-dash-lg\" viewBox=\"0 0 16 16\">\r\n");
      out.write("                                <path d=\"M0 8a1 1 0 0 1 1-1h14a1 1 0 1 1 0 2H1a1 1 0 0 1-1-1z\"/>\r\n");
      out.write("                            </svg>\r\n");
      out.write("                        </span>\r\n");
      out.write("                    </dt>\r\n");
      out.write("                    <dd class=\"ddd\"><span class=\"pInfoText\">\r\n");
      out.write("                        ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ product.product_sizeinfo }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("                    </span> <br></dd>\r\n");
      out.write("                    <hr>\r\n");
      out.write("                    <dt>\r\n");
      out.write("                        <b>Select Size</b>\r\n");
      out.write("                        <select name=\"\" id=\"selectSize\" class=\"selectSize\" style=\"width: 140px; float: right; margin-right: 30px;\" >\r\n");
      out.write("                            <option value=\"\">선택안함</option>\r\n");
      out.write("                           	");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                            ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                            ");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                            ");
      if (_jspx_meth_c_005fif_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                            ");
      if (_jspx_meth_c_005fif_005f4(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                            ");
      if (_jspx_meth_c_005fif_005f5(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                        </select> <br>\r\n");
      out.write("                    </dt><hr>\r\n");
      out.write("                    <dt class=\"pOrigin\">\r\n");
      out.write("                        <div id=\"origin\" class=\"selectedPList\">\r\n");
      out.write("                       		<input type=\"hidden\" class=\"product_no\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.product_no }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("                       		<input type=\"hidden\" class=\"product_type\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.product_type }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("                            <span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ product.product_name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("<b class=\"selectedSize\"></b> </span>\r\n");
      out.write("                            <input type=\"number\" class=\"quantity\" id=\"pQuan\" name=\"pQuan\" value=\"1\" min=\"1\"> <!-- input value 값 ??  -->\r\n");
      out.write("                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/xx.png\" alt=\"\" style=\"width: 15px; height: 15px; margin-right: 5px;\" class=\"pdeleteBtn\" >\r\n");
      out.write("                            <span>￦</span><span class=\"pPrice\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ product.product_price }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("                            <input type=\"hidden\" class=\"selSize\" />\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </dt>\r\n");
      out.write("                    <dt class=\"pResult\">\r\n");
      out.write("                    </dt>\r\n");
      out.write("\r\n");
      out.write("                    <dt><br /><br />\r\n");
      out.write("                        <div>   \r\n");
      out.write("                            <b>Total :</b> <span id=\"won\">0</span> <span class=\"totalPD\"></span> <span id=\"totalQ\"></span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </dt>\r\n");
      out.write("                </dl>\r\n");
      out.write("				<div class='btnArea'>\r\n");
      out.write("	                <button class=\"btn\" onclick=\"addCart();\">add to cart</button>\r\n");
      out.write("	                <button class=\"btn\" onclick=\"goBuy();\">buy now</button>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"review_list\" style=\"clear:both;\">\r\n");
      out.write("        <br><br><br><hr>\r\n");
      out.write("\r\n");
      out.write("        <div style=\"margin-bottom: 15px;\">\r\n");
      out.write("        	<span class=\"underMenu review\" style=\"margin-bottom: 50px;\">REVIEW</span><span class=\"underMenu faq\" style=\"margin-bottom: 50px;\">FAQ</span>\r\n");
      out.write("        </div><hr>\r\n");
      out.write("        \r\n");
      out.write("        <dl id=\"review-table\">\r\n");
      out.write("        	<dt class=\"showArea\">\r\n");
      out.write("				<span class=\"th\">번호</span>\r\n");
      out.write("				<span class=\"th\">제목</span>\r\n");
      out.write("				<span class=\"th\">작성자</span>\r\n");
      out.write("				<span class=\"th\">작성일</span>\r\n");
      out.write("	            <span class=\"accIcon\" style=\"float: right; margin-right: 30px;\">\r\n");
      out.write("                </span>\r\n");
      out.write("            </dt><hr>\r\n");
      out.write("            \r\n");
      out.write("            ");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("        </dl>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        <dl id=\"FAQ-table\">\r\n");
      out.write("            \r\n");
      out.write("	            <dt class=\"showArea-faq\">\r\n");
      out.write("	                주문내역을 확인하고 싶어요.\r\n");
      out.write("	               \r\n");
      out.write("	                <span class=\"accIcon\" style=\"float: right; margin-right: 30px;\">\r\n");
      out.write("	                     <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-plus-lg\" viewBox=\"0 0 16 16\">\r\n");
      out.write("	                          <path d=\"M8 0a1 1 0 0 1 1 1v6h6a1 1 0 1 1 0 2H9v6a1 1 0 1 1-2 0V9H1a1 1 0 0 1 0-2h6V1a1 1 0 0 1 1-1z\"/>\r\n");
      out.write("	                     </svg>\r\n");
      out.write("	                     <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-dash-lg\" viewBox=\"0 0 16 16\">\r\n");
      out.write("	                          <path d=\"M0 8a1 1 0 0 1 1-1h14a1 1 0 1 1 0 2H1a1 1 0 0 1-1-1z\"/>\r\n");
      out.write("	                     </svg>\r\n");
      out.write("	                </span>\r\n");
      out.write("	            </dt>\r\n");
      out.write("            	<dd class=\"dropArea\">\r\n");
      out.write("	            	<div>\r\n");
      out.write("	                	<br />\r\n");
      out.write("	                	<span class=\"faq-text\">\r\n");
      out.write("	                		YKJK 회원일 경우 로그인 후 <br />\r\n");
      out.write("	                		프로필 아이콘 클릭 > MYPAGE > 주문내역에서 <br /> \r\n");
      out.write("	                		주문내역 확인 가능합니다.\r\n");
      out.write("	                	</span>\r\n");
      out.write("	                	\r\n");
      out.write("	            	</div>\r\n");
      out.write("	            </dd><hr>\r\n");
      out.write("	            \r\n");
      out.write("	            <dt class=\"showArea-faq\">\r\n");
      out.write("	                주문현황을 확인하고 싶어요.\r\n");
      out.write("	               \r\n");
      out.write("	                <span class=\"accIcon\" style=\"float: right; margin-right: 30px;\">\r\n");
      out.write("	                     <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-plus-lg\" viewBox=\"0 0 16 16\">\r\n");
      out.write("	                          <path d=\"M8 0a1 1 0 0 1 1 1v6h6a1 1 0 1 1 0 2H9v6a1 1 0 1 1-2 0V9H1a1 1 0 0 1 0-2h6V1a1 1 0 0 1 1-1z\"/>\r\n");
      out.write("	                     </svg>\r\n");
      out.write("	                     <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-dash-lg\" viewBox=\"0 0 16 16\">\r\n");
      out.write("	                          <path d=\"M0 8a1 1 0 0 1 1-1h14a1 1 0 1 1 0 2H1a1 1 0 0 1-1-1z\"/>\r\n");
      out.write("	                     </svg>\r\n");
      out.write("	                </span>\r\n");
      out.write("	            </dt>\r\n");
      out.write("            	<dd class=\"dropArea\">\r\n");
      out.write("	            	<div>\r\n");
      out.write("	                	<br />\r\n");
      out.write("	                	<span class=\"faq-text\">\r\n");
      out.write("	                		YKJK 회원일 경우 로그인 후 프로필 아이콘 클릭 > MYPAGE > 주문내역에서 <br /> \r\n");
      out.write("	                		주문 및 배송현황 확인 가능합니다. <br /><br /> \r\n");
      out.write("	                		\r\n");
      out.write("	                		- 배송준비중 : 결제완료 후 해당 브랜드로부터 상품 발송을 대기중<br /> \r\n");
      out.write("	                		- 배송중 : 브랜드에서 상품 발송 완료<br />\r\n");
      out.write("	                		- 구매완료 : 고객이 상품을 받고 구매완료 신청했을 경우 <br />\r\n");
      out.write("	                	</span>\r\n");
      out.write("	                	\r\n");
      out.write("	            	</div>\r\n");
      out.write("	            </dd><hr>\r\n");
      out.write("	            \r\n");
      out.write("	            <dt class=\"showArea-faq\">\r\n");
      out.write("	                중고상품 결제/결제후엔 어떻게 하나요?\r\n");
      out.write("	               \r\n");
      out.write("	                <span class=\"accIcon\" style=\"float: right; margin-right: 30px;\">\r\n");
      out.write("	                     <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-plus-lg\" viewBox=\"0 0 16 16\">\r\n");
      out.write("	                          <path d=\"M8 0a1 1 0 0 1 1 1v6h6a1 1 0 1 1 0 2H9v6a1 1 0 1 1-2 0V9H1a1 1 0 0 1 0-2h6V1a1 1 0 0 1 1-1z\"/>\r\n");
      out.write("	                     </svg>\r\n");
      out.write("	                     <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-dash-lg\" viewBox=\"0 0 16 16\">\r\n");
      out.write("	                          <path d=\"M0 8a1 1 0 0 1 1-1h14a1 1 0 1 1 0 2H1a1 1 0 0 1-1-1z\"/>\r\n");
      out.write("	                     </svg>\r\n");
      out.write("	                </span>\r\n");
      out.write("	            </dt>\r\n");
      out.write("            	<dd class=\"dropArea\">\r\n");
      out.write("	            	<div>\r\n");
      out.write("	                	<br />\r\n");
      out.write("	                	<span class=\"faq-text\">\r\n");
      out.write("		                	YKJK에서 결제해주시면 판매자에게 전달해드립니다. <br /> \r\n");
      out.write("		                	판매자가 입금 확인 후 상품을 발송할 예정이오니,<br />\r\n");
      out.write("		                	마이페이지 > 주문내역 에서 주문 현황을 확인해주시기 바랍니다.<br />\r\n");
      out.write("	                	</span>\r\n");
      out.write("	            	</div>\r\n");
      out.write("	            </dd><hr>\r\n");
      out.write("	            \r\n");
      out.write("	            <dt class=\"showArea-faq\">\r\n");
      out.write("	                내 정보는 어떻게 수정하나요?\r\n");
      out.write("	               \r\n");
      out.write("	                <span class=\"accIcon\" style=\"float: right; margin-right: 30px;\">\r\n");
      out.write("	                     <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-plus-lg\" viewBox=\"0 0 16 16\">\r\n");
      out.write("	                          <path d=\"M8 0a1 1 0 0 1 1 1v6h6a1 1 0 1 1 0 2H9v6a1 1 0 1 1-2 0V9H1a1 1 0 0 1 0-2h6V1a1 1 0 0 1 1-1z\"/>\r\n");
      out.write("	                     </svg>\r\n");
      out.write("	                     <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-dash-lg\" viewBox=\"0 0 16 16\">\r\n");
      out.write("	                          <path d=\"M0 8a1 1 0 0 1 1-1h14a1 1 0 1 1 0 2H1a1 1 0 0 1-1-1z\"/>\r\n");
      out.write("	                     </svg>\r\n");
      out.write("	                </span>\r\n");
      out.write("	            </dt>\r\n");
      out.write("            	<dd class=\"dropArea\">\r\n");
      out.write("	            	<div>\r\n");
      out.write("	                	<br />\r\n");
      out.write("	                	<span class=\"faq-text\">\r\n");
      out.write("		                	로그인 아이콘 클릭 > 마이페이지 > 회원 정보에서 <br />\r\n");
      out.write("		                	원하시는 정보만 수정할 수 있습니다. <br />\r\n");
      out.write("	                	</span>\r\n");
      out.write("	            	</div>\r\n");
      out.write("	            </dd><hr>\r\n");
      out.write("	            \r\n");
      out.write("	            <dt class=\"showArea-faq\">\r\n");
      out.write("	                리뷰는 어떻게 작성하나요?\r\n");
      out.write("	               \r\n");
      out.write("	                <span class=\"accIcon\" style=\"float: right; margin-right: 30px;\">\r\n");
      out.write("	                     <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-plus-lg\" viewBox=\"0 0 16 16\">\r\n");
      out.write("	                          <path d=\"M8 0a1 1 0 0 1 1 1v6h6a1 1 0 1 1 0 2H9v6a1 1 0 1 1-2 0V9H1a1 1 0 0 1 0-2h6V1a1 1 0 0 1 1-1z\"/>\r\n");
      out.write("	                     </svg>\r\n");
      out.write("	                     <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-dash-lg\" viewBox=\"0 0 16 16\">\r\n");
      out.write("	                          <path d=\"M0 8a1 1 0 0 1 1-1h14a1 1 0 1 1 0 2H1a1 1 0 0 1-1-1z\"/>\r\n");
      out.write("	                     </svg>\r\n");
      out.write("	                </span>\r\n");
      out.write("	            </dt>\r\n");
      out.write("            	<dd class=\"dropArea\" id=\"accordion2\" class=\"collapse2\">\r\n");
      out.write("	            	<div>\r\n");
      out.write("	                	<br />\r\n");
      out.write("	                	<span class=\"faq-text\">\r\n");
      out.write("		                	로그인 아이콘 클릭 > 마이페이지에서 주문하신 상품의 리뷰만 작성하실 수 있습니다. <br /> \r\n");
      out.write("	                		리뷰 내용은 텍스트만 작성할 수 있으며 사용하시는 닉네임으로 등록됩니다. <br />\r\n");
      out.write("	                	</span>\r\n");
      out.write("	                	\r\n");
      out.write("	            	</div>\r\n");
      out.write("	            </dd>\r\n");
      out.write("	            \r\n");
      out.write("	         </dl>   \r\n");
      out.write("	        \r\n");
      out.write("        <hr />\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        <!-- 우선 틀만 잡아놓음 -->\r\n");
      out.write("            <!-- 페이지네이션 (임시) -->\r\n");
      out.write("            ");
      if (_jspx_meth_c_005fout_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fimport_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    \r\n");
      out.write("	<script>\r\n");
      out.write("	\r\n");
      out.write("		$(function() {\r\n");
      out.write("		    $(document).ready(function(){\r\n");
      out.write("		        $('#ex1').zoom();\r\n");
      out.write("		      \r\n");
      out.write("		    });\r\n");
      out.write("		});\r\n");
      out.write("    \r\n");
      out.write("    	// 장바구니에 선택상품 담기\r\n");
      out.write("		function addCart() {\r\n");
      out.write("				if(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty member}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("){\r\n");
      out.write("					alert(\"PLEASE LOGIN\")\r\n");
      out.write("				}else{\r\n");
      out.write("				 var pp = $('.selectedSize').text();\r\n");
      out.write("			 if(pp == \"\"){\r\n");
      out.write("	       		  alert('선택된 항목이 없습니다.');\r\n");
      out.write("	       	  } else {\r\n");
      out.write("        		 if(product_size != \"\"){\r\n");
      out.write("        	   	 var product_size = [];\r\n");
      out.write("        		 $('.selSize').each(function(){\r\n");
      out.write("        			 product_size.push($(this).val());\r\n");
      out.write("        		 })\r\n");
      out.write("        		 \r\n");
      out.write("        		  var order_quantity = [];\r\n");
      out.write("				 $('.quantity').each(function(){\r\n");
      out.write("					 order_quantity.push($(this).val());\r\n");
      out.write("				 })\r\n");
      out.write("        		 var product_no = [];\r\n");
      out.write("				 $('.product_no').each(function(){\r\n");
      out.write("					product_no.push($(this).val()); \r\n");
      out.write("				 	})\r\n");
      out.write("        		 }	\r\n");
      out.write("       	   		$.ajax({\r\n");
      out.write("	       		    method: 'POST',\r\n");
      out.write("	       		    url: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/order/addCartList.or\",\r\n");
      out.write("	       		   	data: {\r\n");
      out.write("						\"product_size\" :  product_size,\r\n");
      out.write("						\"order_quantity\" : order_quantity,\r\n");
      out.write("						\"product_no\" : product_no\r\n");
      out.write("					}, \r\n");
      out.write("					success: function(){\r\n");
      out.write("						// 장바구니 이동 확인\r\n");
      out.write("			        	 if(confirm(\"장바구니에 상품이 담겼습니다. 장바구니로 이동하시겠습니까?\") == true){\r\n");
      out.write("			        	        location.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/order/cart.or\"\r\n");
      out.write("			        	    } else{\r\n");
      out.write("			        	        return ;\r\n");
      out.write("			        	    };\r\n");
      out.write("						}, error : function(){\r\n");
      out.write("							alert(\"실패\");\r\n");
      out.write("						}\r\n");
      out.write("					});    \r\n");
      out.write("	   			 }\r\n");
      out.write("				}\r\n");
      out.write("    	}\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		  // 상품 상세페이지에서 바로 구매\r\n");
      out.write("          function goBuy() {\r\n");
      out.write("        	  if(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty member}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("){\r\n");
      out.write("					alert(\"LOGIN FIRST.\");\r\n");
      out.write("				}else{\r\n");
      out.write("					 var pp = $('.selectedSize').text();\r\n");
      out.write("					 if(pp == \"\"){\r\n");
      out.write("			       		  alert('무엇을 사고 싶은 건데요?');\r\n");
      out.write("			       	  } else {\r\n");
      out.write("						  var buyList = [];\r\n");
      out.write("			        	  $('.selectedPList').each(function(){\r\n");
      out.write("				        	  var product_no = $(this).children('.product_no').val();\r\n");
      out.write("				        	  var cart_quantity = $(this).children('.quantity').val();\r\n");
      out.write("				        	  var cart_size = $(this).children('.selSize').val();\r\n");
      out.write("				        	  var product_name = '");
      if (_jspx_meth_c_005fout_005f1(_jspx_page_context))
        return;
      out.write("';\r\n");
      out.write("				        	  var brand_name = '");
      if (_jspx_meth_c_005fout_005f2(_jspx_page_context))
        return;
      out.write("';\r\n");
      out.write("				        	  var product_price = '");
      if (_jspx_meth_c_005fout_005f3(_jspx_page_context))
        return;
      out.write("';\r\n");
      out.write("				        	  var att_name = '");
      if (_jspx_meth_c_005fout_005f4(_jspx_page_context))
        return;
      out.write("';\r\n");
      out.write("				        	 \r\n");
      out.write("				        	 \r\n");
      out.write("				        	  if(cart_size != \"\"){\r\n");
      out.write("					        	 var product = {\r\n");
      out.write("					        			 'product_no' : product_no,\r\n");
      out.write("					        			 'cart_quantity' : cart_quantity,\r\n");
      out.write("					        			 'cart_size' : cart_size,\r\n");
      out.write("					        			 'product_name' : product_name,\r\n");
      out.write("					        			 'brand_name' : brand_name,\r\n");
      out.write("					        			 'product_price' : product_price,\r\n");
      out.write("					        			 'att_name' : att_name\r\n");
      out.write("					        			 \r\n");
      out.write("					        	 }\r\n");
      out.write("					        	  buyList.push(product);\r\n");
      out.write("				        	  }\r\n");
      out.write("		        		  })\r\n");
      out.write("		        	  \r\n");
      out.write("		        		var data = JSON.stringify(buyList);\r\n");
      out.write("			        \r\n");
      out.write("		        	  \r\n");
      out.write("		        	   $.ajax({\r\n");
      out.write("		       		    method: 'POST',\r\n");
      out.write("		       		    url: '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/order/buyList.or',\r\n");
      out.write("		       		    traditional: true,\r\n");
      out.write("						data: {data}, \r\n");
      out.write("						success: function(data){\r\n");
      out.write("								console.log(\"전송 성공\")\r\n");
      out.write("								location.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/order/order.or?selectedCart_no=\"+data;\r\n");
      out.write("							}, error : function(){\r\n");
      out.write("								console.log(\"실패\");\r\n");
      out.write("							}\r\n");
      out.write("						});        	  \r\n");
      out.write("        	  }\r\n");
      out.write("			}\r\n");
      out.write("        	  			\r\n");
      out.write("		  }\r\n");
      out.write("          \r\n");
      out.write("          \r\n");
      out.write("          /*\r\n");
      out.write("        	 $('.selectedPList').each(function(){\r\n");
      out.write("        		 var product_no = $(this).children('.product_no').val();\r\n");
      out.write("	        	 var cart_quantity = $(this).children('.quantity').val();\r\n");
      out.write("	        	 var cart_size = $(this).children('.selSize').val();\r\n");
      out.write("	        	 var brand_name = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ product.brand_name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\r\n");
      out.write("	        	 var product_name = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ product.product_name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\r\n");
      out.write("	        	 var product_price = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ product.product_price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\r\n");
      out.write("	        	// var att_name = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ attachment[1].att_name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\r\n");
      out.write("	        	  \r\n");
      out.write("        	 })\r\n");
      out.write("        	 \r\n");
      out.write("        	 console.log('구매버튼 자료 확인');\r\n");
      out.write("        	 console.log(product_no);\r\n");
      out.write("        	 console.log(cart_quantity);\r\n");
      out.write("        	 console.log(cart_size);\r\n");
      out.write("        	 console.log(brand_name);\r\n");
      out.write("        	 console.log(product_name);\r\n");
      out.write("        	 console.log(product_price);\r\n");
      out.write("        	 //console.log(att_name);\r\n");
      out.write("\r\n");
      out.write("        	 \r\n");
      out.write("        	 \r\n");
      out.write("         } */\r\n");
      out.write("\r\n");
      out.write("        // $(function() {\r\n");
      out.write("        //     if($('.totalPD').text()== \"\") {\r\n");
      out.write("        //         console.log(\"totalPD::\" + $('.totalPD').text())\r\n");
      out.write("        //         $('#won').text('0')\r\n");
      out.write("        //     }\r\n");
      out.write("        // });\r\n");
      out.write("        \r\n");
      out.write("         $('.pResult img').on('click', function() {\r\n");
      out.write("         	console.log('test');\r\n");
      out.write("             $(this).parent().remove();\r\n");
      out.write("         	totalCalc();\r\n");
      out.write("         });\r\n");
      out.write("            \r\n");
      out.write("        $('#pQuan').on('change', function() {\r\n");
      out.write("            var uuu = $(this).val()\r\n");
      out.write("            \r\n");
      out.write("            // var ggg = $('#ppPrice').text().str.substring(indexStart[2, indexEnd])\r\n");
      out.write("            // var ggg = $('#ppPrice').text()\r\n");
      out.write("            // console.log(uuu);\r\n");
      out.write("            // console.log(ggg);\r\n");
      out.write("            // console.log(uuu*hhh);\r\n");
      out.write("            $(this).siblings('.pPrice').text(thousandComma(uuu*hhh));\r\n");
      out.write("            totalCalc();\r\n");
      out.write("        });\r\n");
      out.write("        var hhh;\r\n");
      out.write("        $(function() {\r\n");
      out.write("            hhh = $('#ppPrice').text();\r\n");
      out.write("            // console.log(hhh);\r\n");
      out.write("            $('#ppPrice').text(thousandComma($('#ppPrice').text()));\r\n");
      out.write("            if($(\"#pQuan\").val() < 1) alert(\"최소 주문수량은 1개 입니다.\");\r\n");
      out.write("        });\r\n");
      out.write("        $('.pOrigin').hide();\r\n");
      out.write("        // $('.pResult').hide();\r\n");
      out.write("        \r\n");
      out.write("        $('#selectSize').on('change', function() {\r\n");
      out.write("            $('.pResult').show();\r\n");
      out.write("            if($('.frmSize.'+$('#selectSize').val()).length == 0){\r\n");
      out.write("                var result = $('#origin').clone(true);\r\n");
      out.write("                result.removeClass('#origin');\r\n");
      out.write("                result.addClass($('#selectSize').val());\r\n");
      out.write("                result.addClass('frmSize');\r\n");
      out.write("                result.find('.selectedSize').text(\"[\" + $('#selectSize').val() + \"]\");\r\n");
      out.write("                result.find('.selSize').val($('#selectSize').val());\r\n");
      out.write("                \r\n");
      out.write("                $('.pResult').append(result);\r\n");
      out.write("                $('.pPrice').each(function(){\r\n");
      out.write("                    $(this).text(thousandComma($(this).text()));\r\n");
      out.write("                });\r\n");
      out.write("            } else {\r\n");
      out.write("                var quan = $('.frmSize.'+$('#selectSize').val()).find('[name=pQuan]');\r\n");
      out.write("                quan.val(parseInt(quan.val()) + 1);\r\n");
      out.write("                var priceTag = quan.siblings('.pPrice');\r\n");
      out.write("                priceTag.text(thousandComma(parseInt((priceTag.text()).replace(',','')) * quan.val()));\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            $('.pResult img').on('click', function() {\r\n");
      out.write("            	console.log('test');\r\n");
      out.write("                $(this).parent().remove();\r\n");
      out.write("            	totalCalc();\r\n");
      out.write("            });\r\n");
      out.write("            \r\n");
      out.write("            totalCalc();\r\n");
      out.write("            $('#won').text('￦')\r\n");
      out.write("            // $('.pResult').$('#selectedSize').text($('#selectSize').val())\r\n");
      out.write("        })\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("       function totalCalc(){\r\n");
      out.write("            var totalPrice = 0;\r\n");
      out.write("            // console.log(\"totalPrice before :: \" + totalPrice);\r\n");
      out.write("            \r\n");
      out.write("            $('.pResult .pPrice').each(function(){\r\n");
      out.write("                // console.log(\"parse : \"+$(this).text());\r\n");
      out.write("                // console.log(\"count = \" + Number(($(this).text()).replace(/,/gm,'')))\r\n");
      out.write("                totalPrice += Number(($(this).text()).replace(/,/gm,''));\r\n");
      out.write("            })\r\n");
      out.write("            \r\n");
      out.write("            // var totalQuan = 0;\r\n");
      out.write("            // $('.pResult #pQuan').each(function() {\r\n");
      out.write("            //     totalQuan += Number($('#pQuan').val())\r\n");
      out.write("            //     $('#totalQ').text(\"(\" + totalQuan + \"개)\")\r\n");
      out.write("            // })\r\n");
      out.write("            $('.totalPD').text(thousandComma(totalPrice));\r\n");
      out.write("            // console.log(\"totalPrice after :: \" + totalPrice);\r\n");
      out.write("       }\r\n");
      out.write("        \r\n");
      out.write("        function thousandComma(x){\r\n");
      out.write("            return x.toString().replace(/\\B(?=(\\d{3})+(?!\\d))/g, \",\");\r\n");
      out.write("        }\r\n");
      out.write("        $('.drop').on('click', function () {\r\n");
      out.write("        	$(this).next('.ddd').slideToggle(300);\r\n");
      out.write("        	\r\n");
      out.write("            // +, - 아이콘 바꾸기\r\n");
      out.write("            var plus = $(this).children('span').children('.bi-plus-lg');\r\n");
      out.write("            var dash = $(this).children('span').children('.bi-dash-lg');\r\n");
      out.write("            if ( dash.css('display') == 'none' ) {\r\n");
      out.write("                dash.css('display', 'inline-block');\r\n");
      out.write("                plus.css('display', 'none');\r\n");
      out.write("            } else {\r\n");
      out.write("                plus.css('display', 'inline-block');\r\n");
      out.write("                dash.css('display', 'none');\r\n");
      out.write("            }\r\n");
      out.write("            // if ($(this).hasClass('on')) {\r\n");
      out.write("            //     slideUp();\r\n");
      out.write("            // } else {\r\n");
      out.write("            //     slideUp();\r\n");
      out.write("            //     $(this).addClass('on').next().slideDown();\r\n");
      out.write("            // }\r\n");
      out.write("            // function slideUp() {\r\n");
      out.write("            //     $('.drop').removeClass('on').next().slideUp();\r\n");
      out.write("            // };\r\n");
      out.write("        });\r\n");
      out.write("        $(function() {\r\n");
      out.write("        	$('#imgDetail').children().children().attr('src', $('#contentImg1').attr('src'));\r\n");
      out.write("        });\r\n");
      out.write("        $('#contentImgArea1').on('click', function() { \r\n");
      out.write("			$('#imgDetail').children().children().attr('src', $('#contentImg1').attr('src'));\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		$('#contentImgArea2').on('click', function() {\r\n");
      out.write("			$('#imgDetail').children().children().attr('src', $('#contentImg2').attr('src'));\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		$('#contentImgArea3').on('click', function() {\r\n");
      out.write("			$('#imgDetail').children().children().attr('src', $('#contentImg3').attr('src'));\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		$('#contentImgArea4').on('click', function() {\r\n");
      out.write("			$('#imgDetail').children().children().attr('src', $('#contentImg4').attr('src'));\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		// icon, review-content toggle\r\n");
      out.write("		$('.showArea, .showArea-faq').on('click', function() {\r\n");
      out.write("			$(this).next('.dropArea').slideToggle(300);\r\n");
      out.write("            // +, - 아이콘 바꾸기\r\n");
      out.write("            var plus = $(this).children('.icon-td').children('span').children('.bi-plus-lg');\r\n");
      out.write("            var dash = $(this).children('.icon-td').children('span').children('.bi-dash-lg');\r\n");
      out.write("			\r\n");
      out.write("            console.log(plus);\r\n");
      out.write("            console.log(dash);\r\n");
      out.write("            \r\n");
      out.write("            if ( dash.css('display') == 'none' ) {\r\n");
      out.write("                dash.css('display', 'block');\r\n");
      out.write("                plus.css('display', 'none');\r\n");
      out.write("            } else {\r\n");
      out.write("                plus.css('display', 'block');\r\n");
      out.write("                dash.css('display', 'none');\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("		\r\n");
      out.write("		// REVIEW 클릭 시 리뷰 테이블만 보이기\r\n");
      out.write("		$('.review').on('click', function() {\r\n");
      out.write("			$('#FAQ-table').css('display', 'none');\r\n");
      out.write("			$('#review-table').css('display', 'block');\r\n");
      out.write("			$(this).css({\r\n");
      out.write("				'text-decoration': 'underline'\r\n");
      out.write("			});\r\n");
      out.write("			$(this).siblings('.faq').css({\r\n");
      out.write("				'text-decoration': 'none'\r\n");
      out.write("			});\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		// FAQ 클릭 시 FAQ 테이블만 보이기\r\n");
      out.write("		$('.faq').on('click', function() {\r\n");
      out.write("			$('#review-table').css('display', 'none');\r\n");
      out.write("			$('#FAQ-table').css('display', 'block');\r\n");
      out.write("			$(this).css({\r\n");
      out.write("				'text-decoration': 'underline'\r\n");
      out.write("			});\r\n");
      out.write("			$(this).siblings('.review').css({\r\n");
      out.write("				'text-decoration': 'none'\r\n");
      out.write("			});\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		$(function() {\r\n");
      out.write("			\r\n");
      out.write("			var str = $('#currPage').text();\r\n");
      out.write("			// var index = str.indexOf('currPage');\r\n");
      out.write("			\r\n");
      out.write("			// var result = str.substring(index+11, index+12);\r\n");
      out.write("			console.log(str);\r\n");
      out.write("			\r\n");
      out.write("			if ( str > 1 ) {\r\n");
      out.write("				var offset = $(\".review_list\").offset();\r\n");
      out.write("	        	$('html, body').animate({scrollTop : offset.top}, 50);\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("			\r\n");
      out.write("	\r\n");
      out.write("			\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("	\r\n");
      out.write("		\r\n");
      out.write("		 \r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fimport_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f0 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f0_reused = false;
    try {
      _jspx_th_c_005fimport_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f0.setParent(null);
      // /WEB-INF/views/product/brandDetail.jsp(13,4) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f0.setUrl("../common/styler.jsp");
      int[] _jspx_push_body_count_c_005fimport_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f0 = _jspx_th_c_005fimport_005f0.doStartTag();
        if (_jspx_th_c_005fimport_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f0);
      _jspx_th_c_005fimport_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fimport_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f1 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f1_reused = false;
    try {
      _jspx_th_c_005fimport_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f1.setParent(null);
      // /WEB-INF/views/product/brandDetail.jsp(23,1) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f1.setUrl("../common/header.jsp");
      int[] _jspx_push_body_count_c_005fimport_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f1 = _jspx_th_c_005fimport_005f1.doStartTag();
        if (_jspx_th_c_005fimport_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f1);
      _jspx_th_c_005fimport_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/product/brandDetail.jsp(29,13) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/product/brandDetail.jsp(29,13) '${attachment}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${attachment}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/product/brandDetail.jsp(29,13) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("a");
      // /WEB-INF/views/product/brandDetail.jsp(29,13) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVarStatus("vs");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("	                <div id=\"contentImgArea");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vs.count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" class=\"imgInput\">\r\n");
            out.write("	                    <img src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/resources/images/productImgUpload/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ a.att_name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" \r\n");
            out.write("	                        id=\"contentImg");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vs.count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" style=\"height: 150px; width: 120px;\"/>\r\n");
            out.write("	                </div>\r\n");
            out.write("                ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/product/brandDetail.jsp(86,28) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ product.product_stock_s != 0}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                            	<option value=\"S\">S</option>\r\n");
          out.write("                            ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/product/brandDetail.jsp(89,28) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ product.product_stock_s == 0}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                            	<option value=\"\">S - 품절</option>\r\n");
          out.write("                            ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /WEB-INF/views/product/brandDetail.jsp(92,28) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ product.product_stock_m != 0}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                            	<option value=\"M\">M</option>\r\n");
          out.write("                            ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent(null);
      // /WEB-INF/views/product/brandDetail.jsp(95,28) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ product.product_stock_m == 0}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                            	<option value=\"\">M - 품절</option>\r\n");
          out.write("                            ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f4 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f4_reused = false;
    try {
      _jspx_th_c_005fif_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f4.setParent(null);
      // /WEB-INF/views/product/brandDetail.jsp(98,28) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ product.product_stock_l != 0}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f4 = _jspx_th_c_005fif_005f4.doStartTag();
      if (_jspx_eval_c_005fif_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                            	<option value=\"L\">L</option>\r\n");
          out.write("                            ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
      _jspx_th_c_005fif_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f5 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f5_reused = false;
    try {
      _jspx_th_c_005fif_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f5.setParent(null);
      // /WEB-INF/views/product/brandDetail.jsp(101,28) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f5.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ product.product_stock_l == 0}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f5 = _jspx_th_c_005fif_005f5.doStartTag();
      if (_jspx_eval_c_005fif_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                            	<option value=\"\">L - 품절</option>\r\n");
          out.write("                            ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f5.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f5);
      _jspx_th_c_005fif_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f5, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /WEB-INF/views/product/brandDetail.jsp(152,12) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/product/brandDetail.jsp(152,12) '${ review }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${ review }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/product/brandDetail.jsp(152,12) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("r");
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("            	<dt class=\"showArea\">\r\n");
            out.write("					<span class=\"th\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ r.review_no }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span>\r\n");
            out.write("					<span class=\"th\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ r.review_title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span>\r\n");
            out.write("					<span class=\"th\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ r.member_nickname }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span>\r\n");
            out.write("					<span class=\"th\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ r.review_date }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span>\r\n");
            out.write("		            <span class=\"accIcon\" style=\"float: right; margin-right: 30px;\">\r\n");
            out.write("		                 <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-plus-lg\" viewBox=\"0 0 16 16\">\r\n");
            out.write("		                      <path d=\"M8 0a1 1 0 0 1 1 1v6h6a1 1 0 1 1 0 2H9v6a1 1 0 1 1-2 0V9H1a1 1 0 0 1 0-2h6V1a1 1 0 0 1 1-1z\"/>\r\n");
            out.write("		                 </svg>\r\n");
            out.write("	                     <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-dash-lg\" viewBox=\"0 0 16 16\">\r\n");
            out.write("	                          <path d=\"M0 8a1 1 0 0 1 1-1h14a1 1 0 1 1 0 2H1a1 1 0 0 1-1-1z\"/>\r\n");
            out.write("	                     </svg>\r\n");
            out.write("	                </span>\r\n");
            out.write("	            </dt>\r\n");
            out.write("	           	<dd class=\"dropArea\">\r\n");
            out.write("	            	<div>\r\n");
            out.write("	                	<br />\r\n");
            out.write("	                	<span class=\"review-content\">\r\n");
            out.write("		                	");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ r.review_contents }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\r\n");
            out.write("	                	</span>\r\n");
            out.write("	            	</div>\r\n");
            out.write("	            </dd><hr>\r\n");
            out.write("            ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fescapeXml_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f0_reused = false;
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent(null);
      // /WEB-INF/views/product/brandDetail.jsp(311,12) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageBar}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/views/product/brandDetail.jsp(311,12) name = escapeXml type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setEscapeXml(false);
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fescapeXml_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      _jspx_th_c_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fimport_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f2 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f2_reused = false;
    try {
      _jspx_th_c_005fimport_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f2.setParent(null);
      // /WEB-INF/views/product/brandDetail.jsp(319,0) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f2.setUrl("../common/footer.jsp");
      int[] _jspx_push_body_count_c_005fimport_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f2 = _jspx_th_c_005fimport_005f2.doStartTag();
        if (_jspx_th_c_005fimport_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f2);
      _jspx_th_c_005fimport_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f1_reused = false;
    try {
      _jspx_th_c_005fout_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f1.setParent(null);
      // /WEB-INF/views/product/brandDetail.jsp(392,35) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ product.product_name }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f1 = _jspx_th_c_005fout_005f1.doStartTag();
      if (_jspx_th_c_005fout_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
      _jspx_th_c_005fout_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f2 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f2_reused = false;
    try {
      _jspx_th_c_005fout_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f2.setParent(null);
      // /WEB-INF/views/product/brandDetail.jsp(393,33) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f2.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ product.brand_name }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f2 = _jspx_th_c_005fout_005f2.doStartTag();
      if (_jspx_th_c_005fout_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f2);
      _jspx_th_c_005fout_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f3 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f3_reused = false;
    try {
      _jspx_th_c_005fout_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f3.setParent(null);
      // /WEB-INF/views/product/brandDetail.jsp(394,36) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f3.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ product.product_price}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f3 = _jspx_th_c_005fout_005f3.doStartTag();
      if (_jspx_th_c_005fout_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f3);
      _jspx_th_c_005fout_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f4 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f4_reused = false;
    try {
      _jspx_th_c_005fout_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f4.setParent(null);
      // /WEB-INF/views/product/brandDetail.jsp(395,31) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f4.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ attachment[1].att_name }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f4 = _jspx_th_c_005fout_005f4.doStartTag();
      if (_jspx_th_c_005fout_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f4);
      _jspx_th_c_005fout_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f4_reused);
    }
    return false;
  }
}
