/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.70
 * Generated at: 2023-01-29 15:43:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.order;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class order_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_0;

static {
  _jspx_fnmap_0= org.apache.jasper.runtime.ProtectedFunctionMapper.getMapForFunction("fn:length", org.apache.taglibs.standard.functions.Functions.class, "length", new Class[] {java.lang.Object.class});
}

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/C:/ThisIsJavaSecondEdition/eclipse-workspace/project3_team3/apache-tomcat-9_0_70/wtpwebapps/YKJK/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/ThisIsJavaSecondEdition/eclipse-workspace/project3_team3/apache-tomcat-9_0_70/wtpwebapps/YKJK/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1674809180567L));
    _jspx_dependants.put("jar:file:/C:/ThisIsJavaSecondEdition/eclipse-workspace/project3_team3/apache-tomcat-9_0_70/wtpwebapps/YKJK/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("   <meta charset=\"utf-8\">\r\n");
      out.write("   <meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\r\n");
      out.write("   <title>주문 페이지</title>\r\n");
      out.write("   <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("   <script src=\"http://dmaps.daum.net/map_js_init/postcode.v2.js\"></script>\r\n");
      out.write("   \r\n");
      out.write("	<script type=\"text/javascript\" src=\"https://code.jquery.com/jquery-1.12.4.min.js\" ></script>\r\n");
      out.write("	<script type=\"text/javascript\" src=\"https://cdn.iamport.kr/js/iamport.payment-1.1.5.js\"></script>\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("   <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/order.css\"/>\r\n");
      out.write("   ");
      if (_jspx_meth_c_005fimport_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write(" \r\n");
      out.write("<body>\r\n");
      if (_jspx_meth_c_005fimport_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<div id=\"backbody order\">\r\n");
      out.write("   <div id=\"frame1\" style=\"align: center;\">\r\n");
      out.write("      <div>\r\n");
      out.write("         <div id=\"frame2\">\r\n");
      out.write("            <span style=\"font-size:15pt; font-weight: bold;\">주문서 작성</span>\r\n");
      out.write("            <span class=\"home\">장바구니&nbsp;&nbsp;&nbsp;>&nbsp;&nbsp;&nbsp;<b>주문서 작성&nbsp;&nbsp;&nbsp;</b>>&nbsp;&nbsp;&nbsp;주문 완료</span>\r\n");
      out.write("         </div>\r\n");
      out.write("       \r\n");
      out.write("         <div>\r\n");
      out.write("            <table class=\"calculation1\" style=\"margin-top:20px;\">\r\n");
      out.write("            <thead>\r\n");
      out.write("               <tr>\r\n");
      out.write("                  <th colspan=\"10\" style=\"text-align: left; padding-left: 10px; padding-top: 20px;\">주문상품(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:length(cart)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
      out.write(")</th>\r\n");
      out.write("               </tr>\r\n");
      out.write("               \r\n");
      out.write("               <tr>\r\n");
      out.write("                  <th colspan=\"10\" style=\"text-align: left; padding-left: 10px; color: gray; padding-top: 30px; border-bottom: solid 1px #e0e0eb;\">상품정보</th>\r\n");
      out.write("               </tr>\r\n");
      out.write("         \r\n");
      out.write("               <tr class=\"tHead\">\r\n");
      out.write("                  <th colspan=\"2\" id=\"pInfo\">item</th>\r\n");
      out.write("                  <th id=\"pPrice\">price</th>\r\n");
      out.write("                  <th id=\"pQuan\">quantity</th>\r\n");
      out.write("               </tr>\r\n");
      out.write("            </thead>\r\n");
      out.write("   \r\n");
      out.write("            <tbody>\r\n");
      out.write("            ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("            </tbody>\r\n");
      out.write("         </table>    <br />\r\n");
      out.write("         \r\n");
      out.write("         \r\n");
      out.write("         \r\n");
      out.write("         <table class=\"calculation2\">\r\n");
      out.write("            <tr style=\"background-color: #fafafa;\">\r\n");
      out.write("               <th style=\"width: 300px;\">총 상품금액</th>\r\n");
      out.write("               <th style=\"width: 300px;\">총 배송비</th>\r\n");
      out.write("               <th style=\"width: 300px; padding: 22px 0;\"><span>총 결제금액</span></th>\r\n");
      out.write("            </tr>\r\n");
      out.write("            \r\n");
      out.write("            <tr style=\"background-color: #fff;\">\r\n");
      out.write("               <td style=\"padding: 22px 0;\"><span class=\"totalPrice price\" id=\"price\" ></span>원</td>\r\n");
      out.write("               <td><span class=\"price\" id=\"price\"></span>무료</td>\r\n");
      out.write("               <td><span class=\"totalPrice price\" id=\"price \"></span>원</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("         </table>\r\n");
      out.write("         <br /><br /><br />\r\n");
      out.write("            \r\n");
      out.write("         </div>\r\n");
      out.write("         \r\n");
      out.write("         <table class=\"delivery\">\r\n");
      out.write("            <thead>\r\n");
      out.write("               <tr>\r\n");
      out.write("                  <th colspan=\"10\">배송지 정보</th>\r\n");
      out.write("               </tr>\r\n");
      out.write("               \r\n");
      out.write("               <tr>\r\n");
      out.write("                  <td class=\"deliverytd\">주문고객</td>\r\n");
      out.write("                  <td>\r\n");
      out.write("                     ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${m.member_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("                  </td>\r\n");
      out.write("               </tr>\r\n");
      out.write("               \r\n");
      out.write("               <tr>\r\n");
      out.write("                  <td class=\"deliverytd\">수령인&nbsp;<span style=\"color: red\">*</span></td>\r\n");
      out.write("                  <td><input class=\"underline recipient\" type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${m.member_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" required=\"required\" /></td>\r\n");
      out.write("               </tr>\r\n");
      out.write("               \r\n");
      out.write("               <tr>\r\n");
      out.write("                  <td class=\"deliverytd\">주소&nbsp;<span style=\"color: red\">*</span></td>\r\n");
      out.write("                  \r\n");
      out.write("                  <td>\r\n");
      out.write("                    <!--  <input class=\"underline\" type=\"text\" id=\"postnum1\" size=\"10\" maxlength=\"5\" />\r\n");
      out.write("                     &nbsp; -->\r\n");
      out.write("                     \r\n");
      out.write("                     \r\n");
      out.write("                     <input class=\"underline\" type=\"text\" id=\"addr1\" size=\"40\" placeholder=\"주소\" required=\"required\" style=\"margin-bottom: 10px;\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${m.address[0]}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("                     <div class=\"btn default postSearch\" id=\"postnum2\" onclick=\"addrSearch();\">주소 찾기</div>\r\n");
      out.write("                     <br />\r\n");
      out.write("                     <input class=\"underline\" type=\"text\" id=\"addr2\" size=\"56\" placeholder=\"상세주소\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${m.address[1]}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("                  </td>\r\n");
      out.write("               </tr>\r\n");
      out.write("               \r\n");
      out.write("               <tr>\r\n");
      out.write("                  <td class=\"deliverytd\">휴대전화&nbsp;<span style=\"color: red\">*</span></td>\r\n");
      out.write("                  <td><input class=\"underline phoneNo\" type=\"text\" placeholder=\"010-1234-5678\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${m.phone}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/></td>\r\n");
      out.write("               </tr>\r\n");
      out.write("               <tr>\r\n");
      out.write("                  <td class=\"deliverytd\">이메일&nbsp;<span style=\"color: red\">*</span></td>\r\n");
      out.write("                  <td>\r\n");
      out.write("                  <input type=\"hidden\" class=\"fullEmail\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${m.email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("                  <input class=\"underline\" id=\"mailId\" type=\"text\" required=\"required\"/> @ <input class=\"underline\" id=\"domainName\" type=\"text\" required=\"required\"/>&nbsp;\r\n");
      out.write("                     <select id=\"emailChoice\">\r\n");
      out.write("                        <option>이메일 선택</option>\r\n");
      out.write("                        <option>daum.net</option>\r\n");
      out.write("                        <option>naver.com</option>\r\n");
      out.write("                        <option>nate.com</option>\r\n");
      out.write("                        <option>gmail.com</option>\r\n");
      out.write("                     </select>\r\n");
      out.write("                  </td>\r\n");
      out.write("               </tr>\r\n");
      out.write("               \r\n");
      out.write("               <tr>\r\n");
      out.write("                  <td class=\"deliverytd\" style=\"border-bottom: solid 1px #e0e0eb; padding-bottom:30px;\">배송메모</td>\r\n");
      out.write("                  <td style=\"border-bottom: solid 1px #e0e0eb; padding-bottom:30px;\">                  \r\n");
      out.write("                     <select id=\"memoChoice\" style=\"height: 30px; font-size: 13px;\">\r\n");
      out.write("                        <option value=\"test1\">배송 시 요청사항을 선택해주세요</option>\r\n");
      out.write("                        <option value=\"test2\">부재시 경비실에 맡겨주세요</option>\r\n");
      out.write("                        <option value=\"test3\">배송 전 연락바랍니다</option>\r\n");
      out.write("                        <option value=\"test4\">직접입력</option>\r\n");
      out.write("                     </select>\r\n");
      out.write("                     <br />\r\n");
      out.write("                     <textarea class=\"textarea order_memo\" cols=\"80\" rows=\"5\"></textarea>\r\n");
      out.write("                  </td>\r\n");
      out.write("               </tr>\r\n");
      out.write("            </thead>\r\n");
      out.write("         </table>\r\n");
      out.write("    \r\n");
      out.write("            \r\n");
      out.write("         <div class=\"payArea\">\r\n");
      out.write("     \r\n");
      out.write("               <div class=\"paymentSelect\">\r\n");
      out.write("       			   <p>결제수단선택</p>\r\n");
      out.write("	               <div class =\"paymentIcon\">\r\n");
      out.write("	                  <label for=\"card\">\r\n");
      out.write("	                  	<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/orderImg/card_icon.png\"/>\r\n");
      out.write("	                  </label>\r\n");
      out.write("	                  <label for=\"samsung\">\r\n");
      out.write("	                 	 <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/orderImg/apple_pay_icon.png\"/>\r\n");
      out.write("	                  </label>\r\n");
      out.write("	                  <label for=\"phone\">\r\n");
      out.write("	                 	 <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/orderImg/phone_icon.png\"/>\r\n");
      out.write("	                  </label>\r\n");
      out.write("	                </div>\r\n");
      out.write("	                <div class =\"paymentRadio\">\r\n");
      out.write("	                  <input type=\"radio\" name=\"cardradio\" id=\"card\" value=\"card\" checked />신용카드\r\n");
      out.write("	                  <input type=\"radio\" name=\"cardradio\" id=\"samsung\" value=\"samsung\"/>삼성페이\r\n");
      out.write("	                  <input type=\"radio\" name=\"cardradio\" id=\"phone\" value=\"phone\"/>휴대폰 결제\r\n");
      out.write("             	    </div>\r\n");
      out.write("	              </div>\r\n");
      out.write("            	\r\n");
      out.write("	            <div class=\"total\">\r\n");
      out.write("	               <div>\r\n");
      out.write("	               		<p>결제정보</p>\r\n");
      out.write("	               </div>\r\n");
      out.write("	               <div class=\"finalPriceArea\">\r\n");
      out.write("		               <span>주문상품금액</span>\r\n");
      out.write("		               <span class=\"won\">&nbsp;원</span> <span class=\"totalPrice fpa-price\"></span>\r\n");
      out.write("		               <input type=\"hidden\" class=\"finalPrice\" id=\"finalPrice\" value=\"\"/>\r\n");
      out.write("	               </div>\r\n");
      out.write("	               <div class=\"btnArea\">\r\n");
      out.write("	               		<button type=\"button\" class=\"btn default payBtn\">결제하기</button>\r\n");
      out.write("	               </div>\r\n");
      out.write("	            </div>\r\n");
      out.write("       	 	</div>\r\n");
      out.write("        	 </div>\r\n");
      out.write("       \r\n");
      out.write("     \r\n");
      out.write("         \r\n");
      out.write("         <div class=\"guideDetail\">\r\n");
      out.write("         	<div class=\"detailTitle\">\r\n");
      out.write("         		<p> 주문 전 확인하세요!</p>\r\n");
      out.write("         	</div>\r\n");
      out.write("         	<div class=\"detailContent\">\r\n");
      out.write("	            <ul>\r\n");
      out.write("	               <li class=\"lifont\">실제 결제 금액에 따라 적립포인트는 변경될 수 있습니다.</li>\r\n");
      out.write("	               <li class=\"lifont\">YKJK는 기본적으로 전 상품 무료 배송입니다.</li>\r\n");
      out.write("	               <li class=\"lifont\">2개 이상 브랜드를 주문하신 경우, 각각 개별 배송됩니다.</li>\r\n");
      out.write("	               <li class=\"lifont\">오프라인 매장과 동시 판매되고 있어 결제완료/입고확정 이후에도 품절이나 발송지연이 있을 수 있습니다.</li>\r\n");
      out.write("	               <li class=\"lifont\">품절 발생 시 문자로 결제취소 또는 재결제에 대해 추가 안내 드리고, 품절취소 고객보상 기준에 따라 보상해 드립니다.</li>\r\n");
      out.write("	            </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("    \r\n");
      out.write("   </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("function calcPrice(){\r\n");
      out.write("	  var sum = 0;\r\n");
      out.write("	  $('.realPrice').each(function(){\r\n");
      out.write("		 var price = Number($(this).val());\r\n");
      out.write("       var quantity = Number($(this).parent().next().children('.result').val());\r\n");
      out.write("	         \r\n");
      out.write("	       sum += price*quantity;\r\n");
      out.write("	  })		  \r\n");
      out.write("	  $('#finalPrice').attr('value', sum);\r\n");
      out.write("	  var check = $('#finalPrice').val();\r\n");
      out.write("	  console.log(\"함수 내부 작동 확인 : \" + check);\r\n");
      out.write("	  \r\n");
      out.write("	  $('.totalPrice').text(thousandComma(sum));\r\n");
      out.write("}\r\n");
      out.write("	\r\n");
      out.write("   $(function(){\r\n");
      out.write("\r\n");
      out.write("	 calcPrice();\r\n");
      out.write("	 console.log(\"===== cal function : \" + $('#finalPrice').val());\r\n");
      out.write("	 \r\n");
      out.write("	  \r\n");
      out.write("	 var totalPrice = $('#finalPrice').val();\r\n");
      out.write("	 console.log(\"실행 확인 : \" + totalPrice);\r\n");
      out.write("		 \r\n");
      out.write("	 // 라디오 값 받아보기 \r\n");
      out.write("	 var pay_method = $(\"[name=cardradio]\").val();\r\n");
      out.write("	 console.log(pay_method);\r\n");
      out.write("	 \r\n");
      out.write("   })\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   // 텍스트 에어리어 값 받아보기\r\n");
      out.write("   $('#memoChoice').on('change', function(){\r\n");
      out.write("	   var order_memo = '없음';\r\n");
      out.write("	   if($('#memoChoice option:selected').val() == \"test4\"){\r\n");
      out.write("		   order_memo = $('.textarea').val();\r\n");
      out.write("		  } else {\r\n");
      out.write("			 order_memo = $('#memoChoice option:selected').text();\r\n");
      out.write("		  }\r\n");
      out.write("	   })\r\n");
      out.write("\r\n");
      out.write("	 \r\n");
      out.write("   \r\n");
      out.write("	// ============== 주소 API 시작 ============== // \r\n");
      out.write("   function addrSearch() {\r\n");
      out.write("       new daum.Postcode({\r\n");
      out.write("           oncomplete: function(data) {\r\n");
      out.write("               // 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.\r\n");
      out.write("   \r\n");
      out.write("               // 각 주소의 노출 규칙에 따라 주소를 조합한다.\r\n");
      out.write("               // 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.\r\n");
      out.write("               var fullAddr = ''; // 최종 주소 변수\r\n");
      out.write("               var extraAddr = ''; // 조합형 주소 변수\r\n");
      out.write("   \r\n");
      out.write("               // 사용자가 선택한 주소 타입에 따라 해당 주소 값을 가져온다.\r\n");
      out.write("               if (data.userSelectedType === 'R') { // 사용자가 도로명 주소를 선택했을 경우\r\n");
      out.write("                   fullAddr = data.roadAddress;\r\n");
      out.write("   \r\n");
      out.write("               } else { // 사용자가 지번 주소를 선택했을 경우(J)\r\n");
      out.write("                   fullAddr = data.jibunAddress;\r\n");
      out.write("               }\r\n");
      out.write("   \r\n");
      out.write("               // 사용자가 선택한 주소가 도로명 타입일때 조합한다.\r\n");
      out.write("               if(data.userSelectedType === 'R'){\r\n");
      out.write("                   //법정동명이 있을 경우 추가한다.\r\n");
      out.write("                   if(data.bname !== ''){\r\n");
      out.write("                       extraAddr += data.bname;\r\n");
      out.write("                   }\r\n");
      out.write("                   // 건물명이 있을 경우 추가한다.\r\n");
      out.write("                   if(data.buildingName !== ''){\r\n");
      out.write("                       extraAddr += (extraAddr !== '' ? ', ' + data.buildingName : data.buildingName);\r\n");
      out.write("                   }\r\n");
      out.write("                   // 조합형주소의 유무에 따라 양쪽에 괄호를 추가하여 최종 주소를 만든다.\r\n");
      out.write("                   fullAddr += (extraAddr !== '' ? ' ('+ extraAddr +')' : '');\r\n");
      out.write("               }\r\n");
      out.write("   \r\n");
      out.write("               // 우편번호와 주소 정보를 해당 필드에 넣는다.\r\n");
      out.write("               $('#postnum1').val(data.zonecode); //5자리 새우편번호 사용\r\n");
      out.write("               \r\n");
      out.write("               $('#addr1').val(fullAddr);\r\n");
      out.write("   \r\n");
      out.write("               // 커서를 상세주소 필드로 이동한다.\r\n");
      out.write("               $('#addr2').focus();\r\n");
      out.write("           }\r\n");
      out.write("       }).open();\r\n");
      out.write("   };\r\n");
      out.write("   // ============== 주소 API 끝 ============== //\r\n");
      out.write(" \r\n");
      out.write("   $(document).ready(function(){\r\n");
      out.write("	  emailSpliter();\r\n");
      out.write("	    // 이메일 선택시, 자동으로 값 들어오게 하기\r\n");
      out.write("      $(\"#emailChoice\").bind(\"change\", function(){\r\n");
      out.write("         $(\"#domainName\").val($(this).val());\r\n");
      out.write("      });\r\n");
      out.write("   });\r\n");
      out.write("   \r\n");
      out.write("	// 배송메모 - 직접 입력 선택시에만 textarea 보여주기 \r\n");
      out.write("	$('#memoChoice').on('change', function(){\r\n");
      out.write("	     var a = $('#memoChoice option:selected').val();\r\n");
      out.write("	     if( a == 'test4') {\r\n");
      out.write("	        $('textarea').show();\r\n");
      out.write("	     } else {\r\n");
      out.write("	        $('textarea').hide();\r\n");
      out.write("	     }\r\n");
      out.write("	});\r\n");
      out.write("    \r\n");
      out.write(" \r\n");
      out.write("	\r\n");
      out.write("	// total price calculator \r\n");
      out.write("	function calcPrice(){\r\n");
      out.write("		  var sum = 0;\r\n");
      out.write("		  $('.realPrice').each(function(){\r\n");
      out.write("			 var price = Number($(this).val());\r\n");
      out.write("	         var quantity = Number($(this).parent().next().children('.result').val());\r\n");
      out.write("		         \r\n");
      out.write("		       sum += price*quantity;\r\n");
      out.write("		  })		  \r\n");
      out.write("		  $('#finalPrice').attr('value', sum);\r\n");
      out.write("		  var check = $('#finalPrice').val();\r\n");
      out.write("		  console.log(\"함수 내부 작동 확인 : \" + check);\r\n");
      out.write("		  \r\n");
      out.write("		  $('.totalPrice').text(thousandComma(sum));\r\n");
      out.write("	 }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	// 결제 수단 버튼 클릭시 value 변경\r\n");
      out.write("	$(\"[name=cardradio]\").click(function(){\r\n");
      out.write("		console.log($(\"[name=cardradio]:checked\").val());\r\n");
      out.write("	})\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   // 천단위 쉼표 함수 선언 \r\n");
      out.write("   function thousandComma(x){\r\n");
      out.write("        return x.toString().replace(/\\B(?=(\\d{3})+(?!\\d))/g, \",\");\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("   // 이메일 스플릿(아이디, 도메인 나누기)\r\n");
      out.write("   function emailSpliter(){\r\n");
      out.write("   		var mailAdd = $('.fullEmail').val();\r\n");
      out.write("   		var at = '@';\r\n");
      out.write("   		var mAdd = mailAdd.split(at);\r\n");
      out.write("   		\r\n");
      out.write("   		$('#mailId').val(mAdd[0]);\r\n");
      out.write("   		$('#domainName').val(mAdd[1]);\r\n");
      out.write("   	 }\r\n");
      out.write("  \r\n");
      out.write("   // ========= 아임포트 API 구역 ========= //\r\n");
      out.write("  \r\n");
      out.write("   $('.payBtn').click(function(){\r\n");
      out.write("	 \r\n");
      out.write("	 // 주문 테이블(O_ORDER)에 담을 데이터 \r\n");
      out.write("	 var receiver_name = $('.recipient').val();		// 수령자 이름\r\n");
      out.write("	 var order_address = $(\"#addr1\").val()+\" \"+$(\"#addr2\").val(); // 배송지 주소 설정\r\n");
      out.write("	 var order_memo = ''; // 배송 메모\r\n");
      out.write("	 	// 메모 설정 조건문\r\n");
      out.write("	   if($('#memoChoice option:selected').val() == \"test4\"){\r\n");
      out.write("		   order_memo = $('.textarea').val();\r\n");
      out.write("		  } else if($('#memoChoice option:selected').val() == \"test1\"){\r\n");
      out.write("		  } else {\r\n");
      out.write("			 order_memo = $('#memoChoice option:selected').text();\r\n");
      out.write("		  }\r\n");
      out.write("	\r\n");
      out.write("   	 var total_price = $('#finalPrice').val();\r\n");
      out.write("   	 var member_no = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${m.member_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\r\n");
      out.write("   	\r\n");
      out.write("   	 // 주문 리스트 테이블(O_ORDER_LIST)에 담을 데이터\r\n");
      out.write("	 // 사이즈 값 배열로 받아보기\r\n");
      out.write("   	 var order_size = [];\r\n");
      out.write("	 $('.order_size').each(function(){\r\n");
      out.write("		 order_size.push($(this).val());\r\n");
      out.write("	 })\r\n");
      out.write("   	 var order_quantity = [];\r\n");
      out.write("	 $('.order_quantity').each(function(){\r\n");
      out.write("		 order_quantity.push($(this).val());\r\n");
      out.write("	 })\r\n");
      out.write("	 var product_no = [];\r\n");
      out.write("	 $('.product_no').each(function(){\r\n");
      out.write("		product_no.push($(this).val()); \r\n");
      out.write("	 	})\r\n");
      out.write(" 	 var cart_no = [];\r\n");
      out.write("	 $('.cart_no').each(function(){\r\n");
      out.write("		cart_no.push($(this).val()); \r\n");
      out.write("	 	})\r\n");
      out.write("	 \r\n");
      out.write("	 \r\n");
      out.write("	 var pay_method = $(\"[name=cardradio]:checked\").val();	 // 결제 수단 변수 설정 \r\n");
      out.write("	 var email = $('#mailId').val();	 // 수령자 이메일 설정(아이디)\r\n");
      out.write("	 var domainName = $('#domainName').val();	  // 수령자 이메일 설정(도메인)\r\n");
      out.write("\r\n");
      out.write("	 var phone = $('.phoneNo').val();	 // 수령자번호 설정\r\n");
      out.write("\r\n");
      out.write("	 var IMP = window.IMP; // 생략가능\r\n");
      out.write("     IMP.init('imp02353224'); // 'iamport' 대신 부여받은 \"가맹점 식별코드\"를 사용\r\n");
      out.write("\r\n");
      out.write("     IMP.request_pay({\r\n");
      out.write("  	    pg : 'inicis', // version 1.1.0부터 지원.\r\n");
      out.write("  	    pay_method : pay_method,\r\n");
      out.write("  	    merchant_uid : 'merchant_' + new Date().getTime(),\r\n");
      out.write("  	    name : 'YKJK',\r\n");
      out.write("  	    amount :100,\r\n");
      out.write("  	    buyer_email : email+\"@\"+domainName,\r\n");
      out.write("  	    buyer_name : receiver_name,\r\n");
      out.write("  	    buyer_tel : phone,\r\n");
      out.write("  	    buyer_addr : order_address,\r\n");
      out.write("  		}, function(rsp) { // callback\r\n");
      out.write("	  	    if ( rsp.success ) {  // 결제 성공 \r\n");
      out.write("	  	        var msg = '결제가 완료되었습니다.';\r\n");
      out.write("\r\n");
      out.write("	  		   $.ajax({\r\n");
      out.write("	  					type: \"POST\",\r\n");
      out.write("	  					url: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/order/paymentSuccess.or\",\r\n");
      out.write("	  					data: { \"receiver_name\" : receiver_name,\r\n");
      out.write("	  							\"order_address\" : order_address,\r\n");
      out.write("	  							\"order_memo\" : order_memo,\r\n");
      out.write("	  							\"total_price\" : 100,\r\n");
      out.write("	  							\"order_size\" : order_size,\r\n");
      out.write("	  							\"order_quantity\" : order_quantity,\r\n");
      out.write("	  							\"product_no\" : product_no,\r\n");
      out.write("	  							\"cart_no\" : cart_no\r\n");
      out.write("	  							}, \r\n");
      out.write("	  							\r\n");
      out.write("	  					success: function(data){\r\n");
      out.write("	  							location.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/order/orderResult.or\"\r\n");
      out.write("	  						}, error : function(){\r\n");
      out.write("	  							console.log(\"실패\");\r\n");
      out.write("	  						}\r\n");
      out.write("	  					});  \r\n");
      out.write("	  	    	\r\n");
      out.write("	  	    	\r\n");
      out.write("  	    } else {\r\n");
      out.write("  	        var msg = rsp.error_msg;\r\n");
      out.write("  	    }\r\n");
      out.write("  	    alert(msg);\r\n");
      out.write("  		});\r\n");
      out.write("     })\r\n");
      out.write("        // ========= 아임포트 API 구역 끝 ========= //\r\n");
      out.write("        \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("</script>\r\n");
      if (_jspx_meth_c_005fimport_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fimport_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f0 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f0_reused = false;
    try {
      _jspx_th_c_005fimport_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f0.setParent(null);
      // /WEB-INF/views/order/order.jsp(20,3) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f0.setUrl("../common/styler.jsp");
      int[] _jspx_push_body_count_c_005fimport_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f0 = _jspx_th_c_005fimport_005f0.doStartTag();
        if (_jspx_th_c_005fimport_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f0);
      _jspx_th_c_005fimport_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fimport_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f1 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f1_reused = false;
    try {
      _jspx_th_c_005fimport_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f1.setParent(null);
      // /WEB-INF/views/order/order.jsp(24,0) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f1.setUrl("../common/header.jsp");
      int[] _jspx_push_body_count_c_005fimport_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f1 = _jspx_th_c_005fimport_005f1.doStartTag();
        if (_jspx_th_c_005fimport_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f1);
      _jspx_th_c_005fimport_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/order/order.jsp(52,12) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/order/order.jsp(52,12) '${cart}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${cart}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/order/order.jsp(52,12) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("a");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("               <tr>\r\n");
            out.write("               <input type=\"hidden\" class=\"cart_no\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${a.cart_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" />\r\n");
            out.write("               <input type=\"hidden\" class=\"product_no\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${a.product_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" />\r\n");
            out.write("                  \r\n");
            out.write("               <!-- Product Image Area -->\r\n");
            out.write("                  <td id=\"tdImg\">\r\n");
            out.write("                  	<img src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/resources/images/productImgUpload/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${a.att_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("                  </td>\r\n");
            out.write("                  \r\n");
            out.write("               <!-- Product Info. Area -->\r\n");
            out.write("                   <td style=\"text-align: left; padding-left: 10px; border-left: none; font-weight: bold;\">\r\n");
            out.write("                   	<span>[");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${a.brand_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("]</span> <br/><span>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${a.product_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(" </span> <br /><br />옵션 : <span>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${a.cart_size}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span>\r\n");
            out.write("                 	<input type=\"hidden\" class=\"order_size\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${a.cart_size}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" />\r\n");
            out.write("                   </td>\r\n");
            out.write("                   \r\n");
            out.write("               <!-- Price Area -->\r\n");
            out.write("                  <td>\r\n");
            out.write("                     <span class=\"price1\" style=\"padding-left: 10px;\">");
            if (_jspx_meth_fmt_005fformatNumber_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write(" </span>&nbsp;￦\r\n");
            out.write("                     <input type=\"hidden\" class=\"realPrice\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${a.product_price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"/>\r\n");
            out.write("                  </td>\r\n");
            out.write("	            <!-- Quantity Area --> \r\n");
            out.write("	                <td style=\"width: 100px;\">                        \r\n");
            out.write("                  		 <input id=\"result\" class=\"result quantityInput order_quantity\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${a.cart_quantity}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" disabled/>\r\n");
            out.write("                 	</td>\r\n");
            out.write("               </tr>\r\n");
            out.write("               ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    boolean _jspx_th_fmt_005fformatNumber_005f0_reused = false;
    try {
      _jspx_th_fmt_005fformatNumber_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatNumber_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/order/order.jsp(70,70) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${a.product_price}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/views/order/order.jsp(70,70) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f0.setPattern("#,###");
      int _jspx_eval_fmt_005fformatNumber_005f0 = _jspx_th_fmt_005fformatNumber_005f0.doStartTag();
      if (_jspx_th_fmt_005fformatNumber_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f0);
      _jspx_th_fmt_005fformatNumber_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatNumber_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatNumber_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fimport_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f2 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f2_reused = false;
    try {
      _jspx_th_c_005fimport_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f2.setParent(null);
      // /WEB-INF/views/order/order.jsp(481,0) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f2.setUrl("../common/footer.jsp");
      int[] _jspx_push_body_count_c_005fimport_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f2 = _jspx_th_c_005fimport_005f2.doStartTag();
        if (_jspx_th_c_005fimport_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f2);
      _jspx_th_c_005fimport_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f2_reused);
    }
    return false;
  }
}
