/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.70
 * Generated at: 2023-01-27 01:49:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.ykjk.ykjkApp.product.model.vo.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/C:/ThisIsJavaSecondEdition/eclipse-workspace/project3_team3/apache-tomcat-9_0_70/wtpwebapps/YKJK/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/ThisIsJavaSecondEdition/eclipse-workspace/project3_team3/apache-tomcat-9_0_70/wtpwebapps/YKJK/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1674781393797L));
    _jspx_dependants.put("jar:file:/C:/ThisIsJavaSecondEdition/eclipse-workspace/project3_team3/apache-tomcat-9_0_70/wtpwebapps/YKJK/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.ykjk.ykjkApp.product.model.vo");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 Attachment att = (Attachment)request.getAttribute("attachment");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/main.css\">\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/asset/js/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/bxslider/4.2.15/jquery.bxslider.min.css\" rel=\"stylesheet\" /> \r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/bxslider/4.2.15/jquery.bxslider.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("        .bx-wrapper {\r\n");
      out.write("            -moz-box-shadow: none;\r\n");
      out.write("            -webkit-box-shadow: none;\r\n");
      out.write("            box-shadow: none;\r\n");
      out.write("            border: 0;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("    \r\n");
      out.write("	<article>\r\n");
      out.write("		<div id=\"main_video\">\r\n");
      out.write("	        <video  src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/main_video_b.mp4\" muted=\"muted\" autoplay=\"autoplay\" loop=\"\"></video>\r\n");
      out.write("	    </div>\r\n");
      out.write("        <div class=\"video_content\">\r\n");
      out.write("            <div class=\"video_Brand\">\r\n");
      out.write("                <p>Go to Brand Shop</p>\r\n");
      out.write("            </div>\r\n");
      out.write("    \r\n");
      out.write("            <div class=\"video_SHand\">\r\n");
      out.write("                <p>Go to Second Hand</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </article>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"product_slide\">\r\n");
      out.write("        <div class=\"slide_wrapper\">\r\n");
      out.write("            \r\n");
      out.write("            <ul class=\"bxslider\">\r\n");
      out.write("                <li><img class=\"img1\" src=\"\" alt=\"\" id=\"product_no\" style=\"width: 100%; height: 100%\"/></li>\r\n");
      out.write("                <li><img class=\"img2\" src=\"\" alt=\"\" id=\"product_no\" style=\"width: 100%; height: 100%\"/></li>\r\n");
      out.write("                <li><img class=\"img3\" src=\"\" alt=\"\" id=\"product_no\" style=\"width: 100%; height: 100%\"/></li>\r\n");
      out.write("                <li><img class=\"img4\" src=\"\" alt=\"\" id=\"product_no\" style=\"width: 100%; height: 100%\"/></li>\r\n");
      out.write("                <li><img class=\"img5\" src=\"\" alt=\"\" id=\"product_no\" style=\"width: 100%; height: 100%\"/></li>\r\n");
      out.write("                <li><img class=\"img6\" src=\"\" alt=\"\" id=\"product_no\" style=\"width: 100%; height: 100%\"/></li>\r\n");
      out.write("                <li><img class=\"img7\" src=\"\" alt=\"\" id=\"product_no\" style=\"width: 100%; height: 100%\"/></li>\r\n");
      out.write("                <li><img class=\"img8\" src=\"\" alt=\"\" id=\"product_no\" style=\"width: 100%; height: 100%\"/></li>\r\n");
      out.write("                <li><img class=\"img9\" src=\"\" alt=\"\" id=\"product_no\" style=\"width: 100%; height: 100%\"/></li>\r\n");
      out.write("                <li><img class=\"img10\" src=\"\" alt=\"\" id=\"product_no\" style=\"width: 100%; height: 100%\"/></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("           \r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("   <script>\r\n");
      out.write("        $(function() {\r\n");
      out.write("\r\n");
      out.write("            $('.bxslider').bxSlider({\r\n");
      out.write("                minSlides: 1,\r\n");
      out.write("                maxSlides: 5,\r\n");
      out.write("                moveSlides: 5,\r\n");
      out.write("                slideWidth: 300,\r\n");
      out.write("                slideMargin: 20,\r\n");
      out.write("                mode: 'horizontal',\r\n");
      out.write("                speed: 1500,\r\n");
      out.write("                pause: 5000,\r\n");
      out.write("                infiniteLoop: true,\r\n");
      out.write("                auto: true,\r\n");
      out.write("                controls: false,\r\n");
      out.write("                pager: false\r\n");
      out.write("                \r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("        $(function(){\r\n");
      out.write("        	$.ajax({\r\n");
      out.write("    			type: \"POST\",\r\n");
      out.write("    			url: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product/selectProductImages.do\",\r\n");
      out.write("    			data: {}, \r\n");
      out.write("				\r\n");
      out.write("    			success: function(data){\r\n");
      out.write("    				console.log(\"data\" ,data);\r\n");
      out.write("    				console.log(\"data[0].att_name\", data[0].att_name);\r\n");
      out.write("    				console.log(\"TOP 10 이미지 불러오기 성공!\")\r\n");
      out.write("    				\r\n");
      out.write("    				$('.bxslider>li>.img1').attr(\"src\", \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/productImgUpload/\"+data[0].att_name);\r\n");
      out.write("    				$('.bxslider>li>.img2').attr(\"src\", \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/productImgUpload/\"+data[1].att_name);\r\n");
      out.write("    				$('.bxslider>li>.img3').attr(\"src\", \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/productImgUpload/\"+data[2].att_name);\r\n");
      out.write("    				$('.bxslider>li>.img4').attr(\"src\", \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/productImgUpload/\"+data[3].att_name);\r\n");
      out.write("    				$('.bxslider>li>.img5').attr(\"src\", \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/productImgUpload/\"+data[4].att_name);\r\n");
      out.write("    			    $('.bxslider>li>.img6').attr(\"src\", \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/productImgUpload/\"+data[5].att_name);\r\n");
      out.write("    				$('.bxslider>li>.img7').attr(\"src\", \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/productImgUpload/\"+data[6].att_name);\r\n");
      out.write("    				$('.bxslider>li>.img8').attr(\"src\", \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/productImgUpload/\"+data[7].att_name);\r\n");
      out.write("    				$('.bxslider>li>.img9').attr(\"src\", \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/productImgUpload/\"+data[8].att_name);\r\n");
      out.write("    			  	$('.bxslider>li>.img10').attr(\"src\", \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/productImgUpload/\"+data[9].att_name);\r\n");
      out.write("    				\r\n");
      out.write("    				$('.bxslider>li>.img1').attr(\"id\", data[0].product_no);\r\n");
      out.write("    				$('.bxslider>li>.img2').attr(\"id\", data[1].product_no);\r\n");
      out.write("    				$('.bxslider>li>.img3').attr(\"id\", data[2].product_no);\r\n");
      out.write("    				$('.bxslider>li>.img4').attr(\"id\", data[3].product_no);\r\n");
      out.write("    				$('.bxslider>li>.img5').attr(\"id\", data[4].product_no);\r\n");
      out.write("    			 	$('.bxslider>li>.img6').attr(\"id\", data[5].product_no);\r\n");
      out.write("    				$('.bxslider>li>.img7').attr(\"id\", data[6].product_no);\r\n");
      out.write("    				$('.bxslider>li>.img8').attr(\"id\", data[7].product_no);\r\n");
      out.write("    				$('.bxslider>li>.img9').attr(\"id\", data[8].product_no);\r\n");
      out.write("    				$('.bxslider>li>.img10').attr(\"id\", data[9].product_no);\r\n");
      out.write("    				\r\n");
      out.write("    				\r\n");
      out.write("    				\r\n");
      out.write("    			},\r\n");
      out.write("    			\r\n");
      out.write("    			error: function(){\r\n");
      out.write("    				alert('TOP 10 이미지 불러오기 실패!');\r\n");
      out.write("  					console.log(\"에러\")\r\n");
      out.write("    			}\r\n");
      out.write("    			\r\n");
      out.write("    		});\r\n");
      out.write("    	}); \r\n");
      out.write("        \r\n");
      out.write("        $('.bxslider>li>img').on('click', function() {\r\n");
      out.write("        	var pType = 1;\r\n");
      out.write("        	var product_no = $(this).attr(\"id\");\r\n");
      out.write("        	console.log(\"product_no=\"+product_no);\r\n");
      out.write("        	location.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product/productDetail.do?product_no=\"+product_no+\"&pType=\"+pType;\r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("    \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        //브랜드 리스트로 화면이동\r\n");
      out.write("        $('.video_Brand').on('click', function() {\r\n");
      out.write("            var pType = 1;\r\n");
      out.write("			location.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product/productList.do?pType=\"+pType;\r\n");
      out.write("        })\r\n");
      out.write("\r\n");
      out.write("        //중고 리스트 화면이동\r\n");
      out.write("        $('.video_SHand').on('click', function() {\r\n");
      out.write("            var pType = 2;\r\n");
      out.write("			location.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product/productList.do?pType=\"+pType;\r\n");
      out.write("        })\r\n");
      out.write("    </script>\r\n");
      out.write("    \r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
